### ISSUE TITLE
Disk subsystem usage optimization - rendering

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/operations#103]
Looking at freshly-created profile for Vial (https://git.openstreetmap.org/chef.git/commitdiff/4bef739) I'd like to share some things from my experience:

Assumption: losing last minute of updates on power failure is tolerable. This is likely true for rendering server (especially proxies), and not true for main database server.

 - synchronuous_commit=off for database gives faster diff insert time; 
 - SSD's on ext4 should be mounted as nobarrier,discard,noatime - this prevents write amplification and gives the SSD chance to live longer, nobarrier makes data ingestion a lot faster for postgres;
 - HDD should be mounted with noatime - nobarrier is probably a bad idea unless it's behind battery-backed RAID;
 - sysctl's vm.dirty_bytes and vm.dirty_background_bytes should be set into size of cache of the SSD drive, so that most database changes reside in memory and still quickly fall through caches when disk commit is issued.

**Comment by tomhughes** [comment]
Sure turning off sync give you faster inserts, by breaking ACID and allowing data loss.

Setting discard in the mount options for SSDs is no longer generally recommended - the recommendation now is to run fstrim once a week or so which is what we do.

Setting noatime has the potential to cause problems and very little benefit over relatime which is the default anyway. It's especially problematic for the tile disk where we use atime for expiry!

Tweaking the vm writeout means you can get very large amounts of uncommitted data, which is well known for causing problems when something eventually triggers the writeout due to linuxes poor handling of background flush for such data.

In any case the mount options aren't actually managed by chef at the moment, and I haven't got around to checking those are optimal yet but nobarrier is the only one I'm likely to consider.

**Comment by pnorman** [comment]
> synchronuous_commit=off for database gives faster diff insert time;

If there are safe PostgreSQL GUCs that can be set, they should be done by osm2pgsql.
