### ISSUE TITLE
Q&A plugin removed from Discourse site

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/operations#1031]
See https://community.openstreetmap.org/t/post-voting-no-longer-available/109090

obviously its the OWGs call to configure the site as it sees fit.

**Comment by tomhughes** [comment]
Why on earth are you raising this here rather than giving the discourse administrators a chance to explain? As far as know there has been no OWG decision relating to this and we have made no such change.

I'm going to apply Occam's razor and suggest it's probably a cock up rather than some sort of conspiracy.

**Comment by Firefishy** [comment]
The plugin was disabled by a site auto upgrade. [The plugin is now disabled by default due to this change](https://github.com/discourse/discourse-post-voting/pull/171).
