### ISSUE TITLE
Top donors as per hosting provider credit policy

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/operations#1041]
The hosting provider credit policy states that the welcome page should credit "the top 1-4 donors as determined by the OWG".

Could you please confirm the current list and clarify where updates to the list appear and who is responsible for changing the website when this happens?

**Comment by pnorman** [comment]
At the meeting we decided on just Fastly as the current list, as they're an order of magnitude higher than the next ones, and it wasn't clear at the time exactly who the next ones were.

Like with the old policy we don't have a process that would automatically trigger re-evaluating the list. Since the OWG doesn't write code I would assume the development community is responsible.

I'm not sure what the process should be for re-evaluating who the top donors are, as we've never had one before. I was thinking it could be done with the budgeting cycle but I don't want add any *more* work to that and it feels like that could lead to a long delay if we get a significant new in-kind donation.

**Comment by lonvia** [comment]
Thanks for the info. PR for website done.

So I take it, it is more a process of triggering the OWG and website from outside for updates. Works for me.
