### ISSUE TITLE
Policy for granting whitelists

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#112]
OWG had a discussion last week about whitelists for tiles and the OSM API, and while we were agreed that such whitelists should be granted only in exceptional circumstances, the rules surrounding them should be transparent.

The rate limiting policy on tiles and the API typically has the worst impact on mapping parties and conferences. OWG wants to support those events, but also wants to ensure that a good quality of service is maintained for all users by limiting over-use.

Recent developments could alleviate API rate limiting, see #36, but whitelisting might still be necessary in some circumstances.

I'm opening this issue to discuss the following proposal for a policy:
1. No whitelist lasts longer than 4 days.
2. Whitelists are granted to events with a minimum of 50 people behind a single IP (i.e: for distributed events, each site counts individually).
3. Whitelists are granted only for mapping parties and OSM conferences.

The technical aspects of implementing the whitelist are details, so please use this issue to discuss the _policy_ - we can work the rest out later.

**Comment by pnorman** [comment]
For the API, what's been key in my mind is that the use is for **editing the map data.** If someone or a group is doing normal heavy map editing they shouldn't be rate limited, be that because the rate limiting doesn't impact them or their IP has been whitelisted.

For the API, it's hard to know what will need whitelisting after #36, which makes it hard to form a policy for it.

Tiles are likely to be rate limited if there's enough users behind one IP, so this may need whitelists. This ties in with #113, and I wonder if makes more sense to settle that first, or if this is independent enough.

Something we should preserve is the right to set whitelists for exceptional internal OSM(F) reasons, e.g. if the DWG needs to run a large redaction.

**Comment by Komzpa** [comment]
For tile whitelists, I think there should not be any, **as a precondition** to that there should be QoS policy for the OSMF, that allows at least one large screen per second of tiles for each user. Until then, any user asking for limit to be lifted should be satisfied, per-IP.

Also I think there should be a way for people to be whitelisted on their own infrastructure if they provide it to OpenStreetMap - otherwise it's more useful for them to not provide it to OSMF and just be selfish. 

There's ongoing discussion at https://github.com/openstreetmap/chef/pull/97 about raising these limits and conditions for that.

**Comment by Pauleosm** [comment]
So you would like to block all the universities and schools that stand usually behind one IP? I think thats a bad idea, you would block all the students that want to use the OSM API for their projects. If you want this then this is a good way.

**Comment by pnorman** [comment]
> So you would like to block all the universities and schools that stand usually behind one IP? I think thats a bad idea, you would block all the students that want to use the OSM API for their projects. If you want this then this is a good way.

I don't see that this would impact universities and schools. If they don't need whitelisting right now, this has no impact. #36 already covers any rate-limiting of mapping activity.

The whitelists which have been needed in the past have been [OSM-related conferences](https://github.com/openstreetmap/chef/commit/522840a0bfbe634c0a1f280391f382b04a40f6e9) and the offices of Telenav and Juno Minsk.

**Comment by pnorman** [comment]
With editors supporting OAuth signed requests, I don't think we need to worry about this for the API. @Firefishy, we're using TOTP cookies which have delt with this on tile.osm.org, right?

**Comment by pnorman** [comment]
> With editors supporting OAuth signed requests, I don't think we need to worry about this for the API.

Closing because of this, and we're not getting white list requests.
