### ISSUE TITLE
Upgrade CPUs in ironbelly

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#1124]
I've purchased 2x  Xeon E5-2690v2 CPUs for upgrading CPUs in ironbelly. My donation to OpenStreetMap ;-)

**Comment by mboeringa** [comment]
@Firefishy 

Should be a nice performance boost after the necessary BIOS upgrade.

BTW, I have dual Xeon E5-2680 v4 on offer for free if you want them. Those are the ones I ripped out of my HP Z840 while replacing them with E5-2699 v4s. They are otherwise just gathering dust here in my house as I don't need them anymore.

They are still in perfect working order, just need a bit of cleaning up of the thermal cooling paste (although I already removed most of it).

These could fit in the **HP ProLiant DL360 Gen9** systems of the spike machines that currently seem to feature E5-2620 v4 with about half the multi-threaded performance of these potential replacements.

I will just need an address where to send these if you want them. Costs for sending on me, as another donation ;-)

**Comment by Firefishy** [comment]
@mboeringa Thank you for the offer. I think in the case of the spike servers we value stability over upgrade. I think the machines have sufficient CPU capacity.

**Comment by mboeringa** [comment]
@Firefishy 

Understandable. If the machine don't need it, there is no sense upgrading them. 

I just noticed that the similar spike machines in Equinix Dublin run Xeon E5-2683 v4 processors, which are almost equivalent to the 2680, so that is why the idea came up.

**Comment by Firefishy** [comment]
CPUs have arrived and are in stock in Catford.

**Comment by Firefishy** [comment]
Decided not worth it. Would rather invest time elsewhere.
