### ISSUE TITLE
SMART failures on errol

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/operations#118]
Errol (dev server) has some SMART failures (or EOL warnings?) on disks. We should replace to avoid issues.

Downtime might be needed, as previous experience with yevaud (which is an identical chassis) says that it might not be possible to identify the disks online.

**Comment by zerebubuth** [comment]
```
The following warning/error was logged by the smartd daemon:

Device: /dev/sg2 [areca_disk#01_enc#01], Failed SMART usage Attribute: 9 Power_On_Hours.

Device info:
WDC WD1003FBYX-01Y7B1, S/N:WD-WMAW30150044, WWN:5-0014ee-2b12e478c, FW:01.01V02, 1.00 TB
```

**Comment by zerebubuth** [comment]
Something went bad while trying to replace the disk yesterday and @Firefishy made a heroic rescue. Thanks!

Is it worth re-attempting this? What should we do if the same thing happens again?

Alternatively, there's a spare disk bay and, if I bring the right screws, I could add in the new disk as a hot-spare?

**Comment by tomhughes** [comment]
Well if the array is RAID0 then we will have to add an extra disk, do a rebuild to that disk, and only then can we pull the old one.

**Comment by Firefishy** [comment]
The OS disks are RAID1, 1 of the disks has reached the SMART cutoff for max-powered-on-hours, it hasn't really failed.

The error when disk was hot-pulled was likely due to controller being silly. RAID controller is ancient.

The RAID was a misnomer why the system would not start up. The issue was XFS for /home required a truly excruciating long time to replay log. Documented issue: http://xfs.org/index.php/XFS_FAQ#Q:_mount_.28or_umount.29_takes_minutes_or_even_hours_-_what_could_be_the_reason_.3F

**Comment by zerebubuth** [comment]
It looks like there aren't actually any current alerts for this disk. So rather than cause more disruption, @Firefishy and I thought it better to wait and see if it alerts again.
