### ISSUE TITLE
Introducing a banner policy

### ISSUE THREAD

**Issue by PedaB** [openstreetmap/operations#150]
There seems to be a need for a policy for adding banners to our main site osm.org for a longer time and @tomhughes feels uncomfortable about being the person responsible to decide who gets a banner (see https://github.com/openstreetmap/openstreetmap-website/pull/1435).

I'd thus like to start a discussion about such a policy and on how to create and introduce it. I honestly am mostly interested to get the FOSSGIS banner up (at least next year) and don't have an answer to the questions raised by Tom, but I would at least like to try and get a discussion going.

Besides there had been a discussion on IRC where such a policy should be discussed at all and who gets to decide about such a policy. From what I read the answer was: Discussion should happen on Operations tracker, so here we go :-)

The questions so far are:
1) who gets a banner?
2) how often can they have one?
3) how long in advance of an event do they get one?

**Comment by imagico** [comment]
A well defined and low volume policy would be to say local chapters can get one banner per year for an OSM related event.

A banner on the main page is fairly prominent and obtrusive so it would IMO be good to strictly limit that to very few situations.

**Comment by tomhughes** [comment]
@imagico that's the kind of thing I had in mind certainly, though the immediate question here relates to a request from a local organisation that is not an official local chapter.

**Comment by imagico** [comment]
Well - _local chapter_ in this context could be defined as either an official OSMF local chapter or an otherwise established organized local OSM community on a national level.

**Comment by zerebubuth** [comment]
As a straw man suggestion, how about a policy like:

1. OSMF-run events can have a maximum of 3 contiguous months on the front page, at a time of the event organisers' choosing.
2. Other OSM-specific events (i.e: those for which OSM is the focus, and constitutes a majority of the talks / workshops) can have a maximum of 1 contiguous month on the front page, at a time of the event organisers' choosing.
3. Banners will be taken down after the event has begin.
4. Banners will be (insert existing standard size here), raster images (no Flash, SVG, animation or active content), and linked to a URL of the organisers' choosing.
5. Banners will be shown on rotation, and each will be dismissable by the user.
6. OWG (or CWG?) reserves the right to not display, or to take down, any banner that it deems unsuitable or inappropriate.

cc @harry-wood, and other CWG members.

What do you think?

**Comment by harry-wood** [comment]
Yeah that's looks broadly in line with what I was thinking.

1) "OSMF-run events"  could be more specific (in case somebody thinks their little event qualifies for a 3 month batter. Not the idea!)  "The annual international OpenStreetMap conference or other such major OSMF-run events"
2) Other qualifying events can request a front page banner. An event qualifies for this if...
* OSM is the focus, and constitutes a majority of the talks / workshops

**Comment by mmd-osm** [comment]
Ads could be a bit more targeted: browser language settings and geo ip location come to mind.

As an example: an ad for a Spanish or German-only conference could be shown only to users who at least understand the language.

**Comment by pnorman** [comment]
Targeting would be nice, but let's try to get a policy which works with what we have and it can be revisited if we gain the ability to target banners to a region or language.

**Comment by zerebubuth** [comment]
> "OSMF-run events" could be more specific (in case somebody thinks their little event qualifies for a 3 month banner. Not the idea!)

At the moment, OSMF only runs the annual global SOTM. If OSMF chose to run another conference, or advertise a separate AGM, then I think that would qualify. Although the organisers might not ask for a full 3 months.

> The event is organised by OSMF members or (preferably) an OSMF local chapter organisation

I think this is a good addition, although I'd drop the "preferably" for the policy itself. I do prefer it when people organise together as a local chapter, but I'm not sure it adds anything to the policy to enshrine that preference there.

> I'm not sure about >50 idea but we need something which is a difficult threshold to reach, because this is a front page banner we're talking about. We don't want a different group advertising their tiny little event every few weeks.

That's why I had included the "reserves the right not to display" bit, so there's a general clause to cover events which aren't significant enough to warrant a front page banner.

I think all the events that we've had banners for in the past have been conferences. Should it be limited to conferences only?

Should we tie it to organisational structure, and allow each local chapter one banner per year for a single qualifying event?

**Comment by pnorman** [comment]
I would prefer to have a preference for local chapters, and have their banners have priority over unaffiliated organizations.

> I think all the events that we've had banners for in the past have been conferences. Should it be limited to conferences only?

Yes, I think so.

> Should we tie it to organisational structure, and allow each local chapter one banner per year for a single qualifying event?

Are you thinking of if a local group organizes multiple events per year?

**Comment by zerebubuth** [comment]
> > Should we tie it to organisational structure, and allow each local chapter one banner per year for a single qualifying event?
>
> Are you thinking of if a local group organizes multiple events per year?

I think the point that @harry-wood was making was that we wouldn't want small or local events such as regular meetups advertised with banners - there's simply too many of them, and they're not of interest to most of the website visitors. So it seems that some form of limit would be required to ensure that only events of international interest get on the front page†.

I'd be happy with a human making that call, but it's probably worth providing some guidance in the policy about what kinds of events are "important enough" to qualify. Harry already mentioned that we could use international attendance as a guide, although that might be hard to judge if the banner is requested before tickets go on general sale.

I think it would work if we restrict the banners to some finite number per year (IIRC, no organisation has asked for more than one per year), and see how it goes. If there's a need to bump that for some additional events, then we can revisit the policy with the benefit of knowing how it's working in practice.

†: I think it would be very interesting to have smaller conferences and local events displayed on the map (possibly with banners), but that's off-topic here, would require code and probably a different policy.

**Comment by pnorman** [comment]
> So it seems that some form of limit would be required to ensure that only events of international interest get on the front page

How about just saying that events need to be of international interest in the policy? If its too vague we can come back and revisit it after its in practice.

**Comment by grinapo** [comment]
You need some time to reach the point where Wikipedia have arrived and use geotargeting for banners. :-P

Until then you may open the doors to all kinds of bitching about how international something is, like the mapping party we do where everyone is invited, of course, internationally, regardless of only a few neighbours would pop up. :-) As for my uncalled for opinion the space should be used for events potentially interesting to at least 50% of the OSM users globally, but that'll rule out almost all OSMF events as well. :-P

**Comment by harry-wood** [comment]
yes "open the doors to all kinds of bitching" is something I'm keen to avoid.

Incidentally I don't think geo-targeting tricks will fix that. I think it would be neat actually, but it might make this policy more tricky. It alleviates the pressure by meaning lots of potentially quite small events can have banners, but then the problem is further down the chain. There'll still need to be criteria and decisions (more decisions!) taken on which little events get local banners over what geo-areas.

zere mentioned events displayed on the map, which reminds me of https://www.openstreetmap.de/karte.html (actually they used to have that displayed on the main www.openstreetmap.de homepage) and this reminds me of the idea of moving the main osm map display to one side to make way for a front page with information about the project, and... oh dear that's a deep rabbit hole.

In the absence of any change like that (short/medium term) I would want to convey a straightforward message as an important part of this policy: _"A front page banners is only for big events. Your diddy little local event is not getting one."_

![screen shot 2017-03-01 at 15 43 36](https://cloud.githubusercontent.com/assets/227525/23467535/38c643d6-fe96-11e6-9a17-550f396a11de.png)

But yes a human making a call is going to be necessary. So to combine these ideas. Lets list some criteria, but "we will apply these criteria with some flexibility, at the discretion of CWG".

**Comment by grinapo** [comment]
@harry-wood Not replying to you specifically just a sidetrack about the local events: Wikipedia have _listed_ local chapters and all country-targeting goes through them, they decide and prioritize and request local banners. In fact, local chapters may request global banners as well, and it is usually involving some local decision process. Then the request is examined on top level, but it's easier since it's pre-processend and pre-filtered already: distributed [hierarchical, actually] decision making.

OSMF may designate accepted local communities anyway [our communities are much more informal than WP's, hardly ever incorporated (or whatever is the proper word)], and those may semi-officially coordinate requests originating from and for their region, or even globally. It could (in theory) prevent random pedestrians to request banners, at least for the usual cases.

**Comment by eest9** [comment]
Will there be a "do not track" policy for banners?

**Comment by tomhughes** [comment]
@eest9 These are banners served by us, not by a third party.

**Comment by tordanik** [comment]
> OSM is the focus, and constitutes a majority of the talks / workshops

This requirement would exclude events such as FOSSGIS where the OSM crowd joins efforts with the open source community. This is despite the fact that the OSM-only subset of FOSSGIS would easily qualify on its own, based on the number of national and international visitors. I'm not sure if that's intentional?

**Comment by harry-wood** [comment]
yes. I can say right now that we would bend the rules for FOSSGIS because they have a long track record of representing OpenStreetMap in Germany. It's an unusual case. They basically _are_ the  "OpenStreetMap Germany" organisation. The event is a big deal for OSM. I think there's no need to account for this in the policy, except to say _"we will apply these criteria with some flexibility, at the discretion of CWG"_.

**Comment by PedaB** [comment]
I'm wondering how criteria 1 has to be read/interpreted. SotM-US would qualify due to English language talks. But most local conferences would be in the local language. FOSSGIS conference usually does not have English talks or at least only very few of them are English. SotM-FR 2018 had no English talk at all.

Perhaps we could even change the requirements for the conference to be organized by a local chapter?!

**Comment by imagico** [comment]
@PedaB - i would disagree with the interpretation that _international OpenStreetMap audience_ equals English language.  For me international means simply more than one country.  FOSSGIS is by definition international because the FOSSGIS represents Germany, Austria and Switzerland and the conference takes place in all three countries.

I see no difference between SotM-US and SotM-FR in that regard.  Both have international visitors and both probably usually also have at least a few international talks.

What i wonder is if 6. means there can be no localization in language based on browser configured preferences.  For multilingual events this could be nice and i think it would be good if the policy would allow this - subject to someone implementing support from this in the website of course.

**Comment by pnorman** [comment]
The reason for "targeting an international OpenStreetMap audience" is that the banners are going to be shown to an international audience. If we look at past banners, all the ones since a code change in 2016 have been for conferences aiming to attract international visitors.

The goal for this requirement is to make clear it's for major events, not small ones like the one we held in Seattle a few years back that just was targeting locals.

> 6. means there can be no localization in language based on browser configured preferences.

Why would it? Localization doesn't prevent static images. In any case, if we had the ability to localize banners and/or target banners by language we'd want to revisit this policy.

**Comment by bhousel** [comment]
FWIW, I'd be pretty ok with just getting rid of the banners completely, since they are hidden by ad blockers now.

**Comment by Zverik** [comment]
I agree with Bryan: since we don't want https://github.com/openstreetmap/openstreetmap-website/pull/1743, banners are blocked for everybody, and we can just drop them, instead of discussing policies for invisible images.

**Comment by HolgerJeromin** [comment]
Not everybody uses adblockers. At least I do not. And using vivaldi browser proves I am not an average user. :-)

**Comment by pnorman** [comment]
As long as we have events that want a banner, we still have a need for a policy.

I've made one change, and that's the addition of criteria 5 to cover events like SOTM Oceania which are not put on by an OSMF local chapter..
-----

The OSMF can place banners on the openstreetmap.org website for large international events. Those that meet the criteria of this policy and request via a pull request in the openstreetmap-website repository it shall have their banner displayed.

The criteria of this policy are

1. Only events targeting an international OpenStreetMap audience shall be displayed
2. OpenStreetMap shall be the focus of events, and constitute a majority of talks or workshops. For large events where there is a distinct OpenStreetMap portion of the event, that portion would qualify on its own, and that OSM portion is a significant part of the total event, the CWG may add the banner at its discretion.
3. OSMF-run events can have a maximum of three contiguous months on the front page, at a time of the event organisers' choosing
4. [Local chapter](https://wiki.osmfoundation.org/wiki/Local_Chapters) run events have a maximum of one contiguous month on the front page, at a time of the event organisers' choosing
5. Events with a [SOTM Quick Licence](https://wiki.osmfoundation.org/wiki/SOTM_Quick_Licence) have a maximum of contiguous month on the front page, at a time of the event organisers' choosing
6. Banners will be taken down after the event has begin.
7. Banners shall be static images, subject to design and technical constraints [in the website documentation](https://github.com/openstreetmap/openstreetmap-website/blob/master/FAQ.md#how-do-i-create-a-banner-to-promote-my-openstreetmap-event), and linked to a URL of the organisers' choosing
8. Banners will be shown on rotation, and each will be dismissable by the user.
9. The Operations Working Group and Communications Working Group reserve the right to not display, or to take down, any banner that it deems unsuitable or inappropriate

This policy does not apply to non-event banners such as fundraising banners, status notices, and downtime notifications.

**Comment by pnorman** [comment]
owg circular started, so removing self-assignment for now
