### ISSUE TITLE
Can't edit/create pages in wiki with the VisualEditor

### ISSUE THREAD

**Issue by n42k** [openstreetmap/operations#163]
When I attempt to edit or create a wiki page with the VisualEditor editor I get an "Unknown error" error, such as the one below.

![osm-wiki-bug](https://cloud.githubusercontent.com/assets/1624180/26373815/f13444e0-3ffa-11e7-87bf-c3f62c8c4580.png)

Potentially relevant information:
My username on the wiki is "N42k".
I don't have a user page.
Tested on Firefox 53 and Chromium 58.

**Comment by harry-wood** [comment]
I just did a test and it worked OK for me. But I think we hit this before, and @Firefishy found it related to some [abuse filter](https://wiki.openstreetmap.org/wiki/Special:AbuseFilter) matching overzealously (I guess that's also confounded by some sort of bug in the way the rejection message is reported because it's presumably not supposed to say "Unknown error")

We have abuse filters which apply only to new wiki users with fewer than five edits, hence I don't see the problem with my user, and it's only cropping up for a few people. [User:N42k only made a couple of edits so far](https://wiki.openstreetmap.org/wiki/Special:Contributions/N42k)

So there's a bug there, but...  workarounds to try: Does creating the page with the "source" editor instead of the visual editor work? [worked for this guy](https://help.openstreetmap.org/questions/51743/why-cant-i-create-a-new-osm-wiki-page). And secondly try to notch up five wiki edits on existing pages and then try again with creating a page. e.g. just make some pointless edits to the Sandbox page. I bet after 5 edits things will work fine (but obviously it is an issue we should fix)

**Comment by n42k** [comment]
Creating the [page](https://wiki.openstreetmap.org/wiki/User:N42k) with the "source" editor worked!

After I made some edits in Sandbox until I had 5 changes, as you said, the visual editor began working on my user page. Unfortunately, it doesn't load on the Sandbox page, leaving me with a stuck full progress bar (left it there for a minute, to be sure). Could it be because it's too big? Does that happen for you, too?

Screenshot:
![screenshot of the stuck loading bar](https://user-images.githubusercontent.com/1624180/27223124-1a656c24-5287-11e7-9707-d6aad2fc2967.png)

**Comment by mmd-osm** [comment]
@n42k : do you still experience this issue? The wiki software has been updated in the meantime, so this may no longer be relevant. In this case, can you close the issue?

**Comment by n42k** [comment]
I have tested the issue again with a new account. It no longer happens.

Good job!
