### ISSUE TITLE
Commercial Use Application

### ISSUE THREAD

**Issue by matthewjonesvsp** [openstreetmap/operations#170]
Hello,

I am currently writing an application that I hope to take to the market eventually. It is written in .Net and is a few Window's Forms. I am just curious to see if there would be any issues. The application would simply show the OpenStreetMap using a .Net map control. 

After this, the user can add points, polygons, and some basic direction or paths. I am new to map coding and this is by far the most success I have had with map providers and controls. 

I have read several posts, but I wanted to reach out.

Respectfully,

**Comment by matthewjonesvsp** [comment]
*Correction - would allow users to place Markets on the visible map provided by OSM.

**Comment by HolgerJeromin** [comment]
You have read https://operations.osmfoundation.org/policies/tiles/ ?

**Comment by matthewjonesvsp** [comment]
Yes I have, but I was hoping someone could explain it a little better. I see where any app that is distributed, I need to make them aware and get their permission. I understand that the Tile policy is there for a reason, but I want to be able to see what steps I need to do in order to be able to include it into a commercial application.

**Comment by mtmail** [comment]
The tile policy doesn't forbid commercial applications, so as long as you adhere to the guidelines you're fine. Make the tile URL configurable. I understand and agree 'heavy usage' and some other terms are not precise enough.

Based on past experience of heavy usage by users and companies the policy says `"Commercial services, or those that seek donations, should be especially aware that access may be withdrawn at any point."` and this is what should concern you if you distribute an application. Something out of your control (e.g. one of your end users) can cause your whole application to get blocked, and all other users will end up unhappy. 

https://wiki.openstreetmap.org/wiki/Blocked_applications has a couple of examples. There are likely more where IP blocks or similar were used because the application couldn't be identified.

All said it's better if you use one of the commercial provider listed in the policy or this page https://switch2osm.org/providers/ Many over a free pricing tier. If your tile usage goes beyond their free tier and starts costing you too much money there's also the option to run your own tile server or have a company install a tile server for you.

(I'm not a member of the operations team. My company does OpenStreetMap work, but doesn't offer tiles).

**Comment by mmd-osm** [comment]
It looks like @woodpeck already answered all of your questions here: https://help.openstreetmap.org/questions/57496/commercial-use-application-in-enterprise-environment  Let's close this one. Thanks.

**Comment by tomhughes** [comment]
From an operations point of view we are not in the business of blessing particular applications and giving them a green light or (mostly) the opposite.

Rather we point people at the published policies and ask that you obey them.

In general applications which fetch tiles in real time in response to users viewing the map are not a problem unless they have very large numbers of users - a far bigger problem is applications which prefetch large numbers of tiles before anybody asks to view them.

Most of the policies are about making sure we can identify you if you do wind up causing a problem, and about ensuring that you can easily move to an alternate provider if we do have to block you.
