### ISSUE TITLE
Use of Recaptcha on the wiki

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#19]
We use Recaptcha on the wiki, but now that it's helping Google Maps digitize house numbers, it's something that we should consider switching away from.

It's used as part of the ConfirmEdit plugin to mediawiki
https://github.com/openstreetmap/chef/blob/master/cookbooks/mediawiki/templates/default/mw-ext-ConfirmEdit.inc.php.erb

http://www.mediawiki.org/wiki/Extension:ConfirmEdit

The mediawiki page has a list of alternative captchas:

* SimpleCaptcha
* FancyCaptcha
* MathCaptcha
* QuestyCaptcha
* ReCaptcha
* Are You a Human

The first three are "Not Recommended". QuestyCaptcha is a customisable list of questions. Are You a Human requires patching the extension.

Thoughts? Or alternative approaches that remove the ConfirmEdit extension?

**Comment by Firefishy** [comment]
Yes, I switched to FancyCaptcha for awhile and got shouted at because blind users were unable to complete the captcha.

**Comment by Firefishy** [comment]
http://wiki.hsr.ch/StefanKeller/ReMAPTCHA

**Comment by Firefishy** [comment]
I have disabled the recaptcha for adding links.

**Comment by harry-wood** [comment]
We still have this problem on the [wiki signup page](https://wiki.openstreetmap.org/w/index.php?title=Special:UserLogin&type=signup) though hey?

The more modern [google No CAPTCHA reCAPTCHA](https://googleonlinesecurity.blogspot.co.uk/2014/12/are-you-robot-introducing-no-captcha.html) doesn't do the address data gathering, it just detects if you're a robot by some mysterious magic:

![](https://upload.wikimedia.org/wikipedia/mediawiki/thumb/4/42/Extension_recaptcha_1.png/350px-Extension_recaptcha_1.png)

Well actually it *does* do the address matching still, but not as often. Only if it needs to fall-back to it. 

And this newer thing is available in [Extension:ReCaptcha](https://www.mediawiki.org/wiki/Extension:ReCaptcha) now, so I guess we just need to grab a newer version of that.

**Comment by pnorman** [comment]
I swore this came up on an unrelated mailing list, but I can't find the reference. Anyways, it didn't have much more info than the mediawiki page.

https://www.mediawiki.org/wiki/Extension:ConfirmEdit#ReCaptcha_.28NoCaptcha.29 says "that this module adds a client side JavaScript code, directly loaded from a server from Google, which already can collect the IP address of the user (combined with other data, too) and can not be limited by a configuration option"

**Comment by harry-wood** [comment]
Well it's going to load javascript from google servers just as the existing (older) recaptcha does, and we have to hope (and are currently hoping) google won't be evil tracking that traffic.

But yeah I see there's an additional option to disallow more direct sending of the user's IP address as part of the data which the magic robot detecting algorithm has to go on. So that's a choice we'd have to make.  I would say, better to send the IP address, because why worry about it, given that we have to trust them anyway when requesting the javascript. Also I imagine it might be better at detecting humans if we _do_ send that info, and therefore less likely to fall-back to showing photos of house numbers (the main thing we're keen to see fixed)  But we could try it out either way
