### ISSUE TITLE
Changeset replication stopped

### ISSUE THREAD

**Issue by pa5cal** [openstreetmap/operations#207]
I think something is wrong here: https://planet.osm.org/replication/changesets/

The changeset replication stopped this morning.
The state.yaml is empty (size 0) and the "Last modified" timestamp is "2018-04-26 05:57"

@zerebubuth

**Comment by zerebubuth** [comment]
Thanks. I restarted it, and it should be working again now.

The error suggests to me that one run may have gone long and been clobbered by a different run:

```
ERROR: Bad file descriptor @ fptr_finalize - /store/planet/replication/changesets/state.yaml.tmp
```

I'm not totally sure what sequence of events led to it making a zero-length file, but I think if I can stop the clobbering then it shouldn't happen in future.

I notice in the script that the `flock` on the state file isn't going to work properly, since the script writes a _new_ state file and moves it into place, and I'm pretty sure that means it's not locked (since it's a different inode now). I need to fix that, probably by having a non-writable, separate lock file.
