### ISSUE TITLE
Make wiki.openstreetmap.org faster

### ISSUE THREAD

**Issue by tordans** [openstreetmap/operations#213]
Please make wiki.openstreetmap.org faster.
The page load time is very bad. 
It makes looking up knowledge unnecessary bothersome.

For reference, two pages that are not used often
- Wikipedia: [81 of 100 Speed points in PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwiki.openstreetmap.org%2Fwiki%2FLandcover&tab=desktop)
- OSM Wiki: [47 of 100 Speed points in PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwiki.openstreetmap.org%2Fwiki%2FLandcover&tab=desktop) with the first being "make the server respond faster".

(This was originally postet at https://github.com/openstreetmap/openstreetmap-website/issues/1856)

**Comment by tomhughes** [comment]
I think you need to be more specific about which pages are a problem, as it doesn't seem noticeably slow to me. 

Obviously crazy pages like Map_Features are slow but I don't see any problem with pages in general.

**Comment by tomhughes** [comment]
The specific page that your pagespeed links point to (https://wiki.openstreetmap.org/wiki/Landcover) is a fairly typical feature page and yes, it takes a few seconds, but it transcludes 21 templates. Some of them probably a number of times.

There's really not a huge amount we can do to speed up crazy pages like that - a typical wikipedia page probably never gets anywhere near that number of templates.

**Comment by tomhughes** [comment]
I don't see much sign of anything unusual in the munin graphs (https://munin.openstreetmap.org/openstreetmap/ouroboros.openstreetmap/index.html) for that period.

There's some unusual spikes on the database for the 8th May but it doesn't seem to have impacted apache at all, or produced unusual cpu loads.

**Comment by tordans** [comment]
Hi!
This is a video showing a 18+ second wait when loading a page: 
https://www.dropbox.com/s/8ac0piivlchhndx/wiki-openstreetmap-is-slow.mov?dl=0 (I will delete it in a week.)
That is really bad!
I don't know about wiki-templates and stuff, but this really should be faster. More Server-Power for CPU or Memory, Caching, Different Templates, Different Template Guidelines, CDN, … – something should be possible.

Without a fast an easy to use wiki the quality of tagging in OSM will go down. [Performance matters](https://developers.google.com/web/fundamentals/performance/why-performance-matters/).

Thanks!

**Comment by tomhughes** [comment]
The hardware really should be more than sufficient - there are 12 cores are 32Gb of memory for something that really doesn't do that much. Sadly mediawiki is well known for being pretty terribly from a performance point of view but there's not much we can do about that.

Things like template guidelines are a matter for the wiki users not an operational issue - no matter how much we beg people to be sensible they insist on constructing ever more elaborate schemes for "standarding" things.

I'm sorry but I really don't think this bug is in any way constructive or useful. You're clearly not interested in a sensible discussion, but rather just want to parrot talking points and treat us like we're some sort of idiots for not pushing a magic "go faster" button that doesn't exist.

**Comment by tordans** [comment]
> I'm sorry but I really don't think this bug is in any way constructive or useful. You're clearly not interested in a sensible discussion, but rather just want to parrot talking points and treat us like we're some sort of idiots for not pushing a magic "go faster" button that doesn't exist.

😢

**Comment by simonpoole** [comment]
Just a note on the side: the WMF spends a lot of money (order of magnitude more than the complete OSMF budget) on making wikipedia "go faster", taking that in to account the results are quite good. It would be nice if it was faster, true, but no actual helpful suggestion outside of hand waving.

**Comment by SomeoneElseOSM** [comment]
@tordans Not that it's an operations issue at all, but maybe one way forward would be to try and persuade wiki editors to use fewer templates?  I've tried to do that in the past from the point of view of making the wiki easier for people to actually make use of, but if speed is a problem too then I'd definitely raise it.  Find a page that's a particular problem; see who caused that problem and talk to them about it.

**Comment by mmd-osm** [comment]
Each rendered wiki pages comes with an embedded wgPageParseReport that includes a break down of the total runtime. When opening the javascript console, you could run the following:

```javascript
mw.config.get('wgPageParseReport').limitreport.timingprofile.forEach(function (e) {console.log(e)});
```

It's like a rough indication what templates are expensive. Don't forget to include verdy_p in that discussion, he's probbaly created most of those templates.

Test Page: https://wiki.openstreetmap.org/wiki/Rhein-Main-Verkehrsverbund/Bus_Fulda

Result:

![grafik](https://user-images.githubusercontent.com/5842757/40176361-6d9e101a-59db-11e8-9b9a-5c4d8272ecf8.png)

**Comment by mmd-osm** [comment]
Some recommendations from verdy_p on the wiki page:

1. Consider using Persistant storage for template expansion
2. Install Translation extension

See relevant parts below, full details on the Wiki user page I posted earlier.

> As well the template expansion for now is not stored on this wiki (it persists only in memory for the time of the page expansion). **Wikipedia uses persistant storage and not just transient caches in memory.** But it cannot be used on this wiki, as it has no storage defined for that (this requires installing an additional extension hook in Mediawiki to change the caching policy and setting up the storage and tune its performance, possibly with SSD frontends, or OS-level filesystem caches with more RAM).

>  For now we would need to install the translation extension (which will use separate pages but will not need using "costly parser functions" to test their existence, that's why we use LangSwitch instead, which does not use any costly parser function, including for handling language fallbacks

**Comment by Adamant36** [comment]
Although only slightly related, I second what @Someone else said about persuading people to use less templetes. Along with the performance ding, some of them, like the tabs templete, make pages hard or impossible to read on mobile. Plus, it requires going through Vardy_P in order to change the pages that have the templetes on them, let alone alter the templetes themselves, and he will just act dismissive off hand. Gate keepers on a public project are never a good thing because they essentially makes it impossible for new or average editors to contribute. Especially if the gate keeper has a bad attitude, an eversion to change, and is unwilling to discuss things. I think following SomeoneElse's advice on templetes would midigate a lot of that. Plus, it would help mobile viewability on some pages alot.

**Comment by grinapo** [comment]
@Adamant36 you mix up templates with bad templates. Not using templates is like copying code instead of using subroutines/functions/procedures. (And unless it is causing serious preformance problems it's even offtopic in this issue.)

**Comment by Adamant36** [comment]
@grinapo I could be. I don't know think so though. So far, a lot of the templates I've seen like the translation one or tabs, cause serious issues and wouldn't need to be used in the first place if the wiki back end was updated or certain extensions were installed. I'm obviously not talking about basic ones like {stub} though. 

For instance, the tab template causes serious problems with viewing the pages that have it on mobile devices, to the point of almost being unreadable, because it breaks word wrapping and the drop down menu thing. According to verdy_p though, people on mobile should just deal with it because they are a small segment anyway and it looks good on desktops. Plus, if it is changed on one page, it would have to be changed on all the translated pages or it will break somehow break things for everyone. According to him those things also apply to pages about things having to do with mobile devices, that I would assume would be mainly viewed by people on those types of devices that he thinks users of don't matter. Plus, He also told me to go away and stop editing the wiki because know one asked me to. 

I see both those things as "serious performance problems." Not being able to read a page that talks about how to do something on a mobile device from the device it is talking is a problem. So is essentially being told to  piss off and having your change reverted by the creator of a template, because the person thinks they are entitled to lord over pages that contain things they put there. Even if it screws things up for other people. 

I'm sure things like that aren't confined to just Verdy_P or templates though, but I do think those specific issues  could at least be dealt with if templates were deprioritized and other things like updating the system or installing more extensions were done. Like the translation extension, which has been requested multiple times over the past couple of years, could be installed. Which would make the template be pointless. 

Anyway, I forgot what I was saying and realized I was rambling. So I'll leave it at.
