### ISSUE TITLE
Add routing.openstreetmap.de to routing engines supported on openstreetmap.org

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/operations#237]
From https://wiki.openstreetmap.org/wiki/Strategic_working_group/New_Routing_services_Guidelines_Proposal

 **Mandatory hard criteria.**
- [X]  Internally supported (whole point of running the OSRM instance)
- [X]  Global scope and coverage - http://routing.openstreetmap.de/about.html
- [X]  Capable of meeting traffic demands - http://routing.openstreetmap.de/about.html and http://routing.openstreetmap.de/munin/
- [X]  Reliable service - http://routing.openstreetmap.de/munin/
- [X]  Up to date data - updated daily

 **Soft / arbitrary criteria.**
- [X]  Speed  - CH based
- [X]  Features - multiple profiles - http://routing.openstreetmap.de/about.html
- [X]  Non-commercial - http://routing.openstreetmap.de/about.html
- [X]  Free and Open - OSRM stack

**Comment by woodpeck** [comment]
routing.openstreetmap.de seems to work well, and with car/bike/foot profiles would be a valuable replacement for the old OSRM on openstreetmap.de which only supports automobile routing, especially since the Mapzen alternatives are gone. @simonpoole - what is needed to make this happen? @datendelphin - is routing.openstreetmap.de ready for this?

**Comment by tomhughes** [comment]
What is needed is for OWG to meet and make a decision.

So good luck with that - the porcine aviators that just went past also wish you good luck.

**Comment by Firefishy** [comment]
@simonpoole We should get back to you quite soon now.
