### ISSUE TITLE
Slow display of tiles

### ISSUE THREAD

**Issue by persep** [openstreetmap/operations#257]
The tiles are displaying very slowly.  Sometimes they load completely and sometimes they don't:

![image](https://user-images.githubusercontent.com/1191676/50007678-f9cc2500-ffb1-11e8-93f9-eb1da51afce4.png)

The output from    https://tile.openstreetmap.org/cgi-bin/debug is:
```tile.openstreetmap.org debug
Server Stats
Cache Server: culebre.openstreetmap.org

Render Server: scorch.openstreetmap.org
Load Average: 12.92

File Status
world_boundaries-spherical.tgz last modified: Fri Dec 9 09:22:40 2016
simplified-land-polygons-complete-3857.zip last modified: Thu Dec 13 08:53:37 2018
ne_110m_admin_0_boundary_lines_land.zip last modified: Fri Dec 9 09:22:44 2016
land-polygons-split-3857.zip last modified: Thu Dec 13 08:53:54 2018
antarctica-icesheet-polygons-3857.zip last modified: Fri Dec 14 07:07:06 2018
antarctica-icesheet-outlines-3857.zip last modified: Fri Dec 14 07:07:11 2018
Browser Request Headers
CONTEXT_DOCUMENT_ROOT: /srv/tile.openstreetmap.org/cgi-bin/
SERVER_SOFTWARE: Apache/2.4.29 (Ubuntu)
CONTEXT_PREFIX: /cgi-bin/
SERVER_SIGNATURE:

Apache/2.4.29 (Ubuntu) Server at tile.openstreetmap.org Port 443

REQUEST_METHOD: GET
SERVER_PROTOCOL: HTTP/1.0
QUERY_STRING: 
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
HTTP_CONNECTION: keep-alive
SERVER_NAME: tile.openstreetmap.org
REMOTE_ADDR: 155.210.4.103
HTTP_VIA: 1.1 culebre.openstreetmap.org:3128 (squid/2.7.STABLE9)
SERVER_PORT: 443
SERVER_ADDR: 176.31.235.79
DOCUMENT_ROOT: /srv/tile.openstreetmap.org/html
SCRIPT_FILENAME: /srv/tile.openstreetmap.org/cgi-bin/debug
SERVER_ADMIN: webmaster@openstreetmap.org
SCRIPT_URI: https://tile.openstreetmap.org/cgi-bin/debug
HTTP_DNT: 1
HTTP_HOST: tile.openstreetmap.org
SCRIPT_URL: /cgi-bin/debug
HTTPS: on
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_CACHE_CONTROL: max-age=0
REQUEST_URI: /cgi-bin/debug
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
GATEWAY_INTERFACE: CGI/1.1
HTTP_X_FORWARDED_FOR: 92.189.187.82, 127.0.0.1
SCRIPT_NAME: /cgi-bin/debug
REMOTE_PORT: 33257
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7
REQUEST_SCHEME: https
```

**Comment by kocio-pl** [comment]
It looks like this week servers drop more tiles than in 2. week deploying new version of OSM Carto, while typically in 3. week dropping tiles should be very small already (compare Week 50 with Week 46):

![screenshot_2018-12-14 munin openstreetmap org render openstreetmap org renderd processed](https://user-images.githubusercontent.com/5439713/50008139-84615400-ffb3-11e8-8b95-a04c8e666593.png)

https://munin.openstreetmap.org/openstreetmap.org/render.openstreetmap.org/renderd_processed.html

**Comment by tomhughes** [comment]
We are monitoring this and expect things to return to normal over the weekend.

**Comment by mmd-osm** [comment]
There's something weird going on, I'm even getting HTTP 404 errors on zoom level 16: https://www.openstreetmap.org/#map=16/42.6464/-87.8529

Is there some known issue with zoom level 16? Zoom level 15 + 17 seem ok from here.

https://c.tile.openstreetmap.org/16/16772/24168.png

![bildschirmfoto von 2018-12-20 21-49-57](https://user-images.githubusercontent.com/5842757/50310107-4bd4e500-04a1-11e9-8e89-6d27804284e4.png)

**Comment by tomhughes** [comment]
That's exactly where I'd expect to see them.

**Comment by mmd-osm** [comment]
Hmmm, not sure I'm following you, could you elaborate a bit?

**Comment by tomhughes** [comment]
The root cause is the replace of the "low zoom" tile disk on orm but in this case the name is a little misleading as it covers everything up to z17.

Zooms 0-15 were fully copied from the old disks (0-12 are complete and 13-15 are probably largely complete for practical purposes) while 16 and 17 were only partially copied.

So 16 and 17 is where I would expect to see any failures. Specifics will of course vary - if 17 is generally quicker to render then it is less likely to happen there for example.

**Comment by kocio-pl** [comment]
I'm still worried what's going on. It seems to me that the problem is **only** with z16 (lately I have not seen missing tiles on any other levels), and even in some important places like Chicago, New York, Mexico City or Buenos Aires:

https://www.openstreetmap.org/#map=16/41.8739/-87.6281
https://www.openstreetmap.org/#map=16/40.7738/-73.9713
https://www.openstreetmap.org/#map=16/19.4358/-99.1374
https://www.openstreetmap.org/#map=16/-34.6100/-58.4000

also outside Americas, like Delhi, Beijing, Tokyo or Canberra:

https://www.openstreetmap.org/#map=16/28.6533/77.2172
https://www.openstreetmap.org/#map=16/39.9040/116.3906
https://www.openstreetmap.org/#map=16/35.6809/139.7684
https://www.openstreetmap.org/#map=16/-35.3082/149.1238

yet not in Pretoria, Istanbul, London, Moscow, Cairo or Warsaw.

**Comment by tomhughes** [comment]
There is no need to keep reporting - we are continuing to monitor the problem and adjust things and will do so until the issue is resolved.

**Comment by kocio-pl** [comment]
I see. I was just not sure if you're aware of this still happening for so long period of time and with such specific range (just one zoom level).

**Comment by tomhughes** [comment]
I've literally had the munin page open in my browsers continuously for the last couple of weeks...

**Comment by tomhughes** [comment]
Oh and @Firefishy made some changes last night that we are waiting to see the effect of during today's peak.
