### ISSUE TITLE
Kiezer struggling

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#299]
Similar to #284, tiles service here has been very slow today. It seems to be a problem with [keizer](https://munin.openstreetmap.org/openstreetmap.org/keizer.openstreetmap.org/index.html)

The network graph shows drops in the expected diurnal cycle of traffic:

![if_eth0-day](https://user-images.githubusercontent.com/360803/57297354-b2b10e80-70cf-11e9-8cf5-8bd9afc6520b.png)

The squid times shows median service times measured in multiple seconds

![squid_times-day](https://user-images.githubusercontent.com/360803/57297431-decc8f80-70cf-11e9-98bd-b8ad14c63888.png)

The CPU chart shows the machine is pretty busy, and that something is stealing from the (presumably virtualised) CPUs.

![cpu-day](https://user-images.githubusercontent.com/360803/57297557-2b17cf80-70d0-11e9-8c69-4995ac55655f.png)

**Comment by tomhughes** [comment]
Sadly we don't have the resources to manage these issues - we have far more caches that we are reasonably able to monitor or manage and much of their performance is outside our control anyway.

**Comment by tomhughes** [comment]
Also because keizer is just one quarter of the German cache we have no way to control the load going to it on an individual basis. I believe kalessin is also getting too much load but the same problem applies.

It's not really something we can solve without a complete redesign of the cache system...

**Comment by tomhughes** [comment]
Sorry @gravitystorm I wasn't necessarily trying to say we should close this... I'm just a bit jaded trying to keep the cache show on the road and finding that every time you fix one machine it moves the problem somewhere else :-(

I'm a bit surprised Poland is on the German cache as I thought it pretty much only did Germany so we could probably move Poland off it.

Germany is always a problem due to the massive load and fact that the "cache" is actually four machines of rather different capabilities being round robined via DNS.

**Comment by tomhughes** [comment]
Hopefully https://github.com/openstreetmap/dns/commit/cef3ef9b25b33b446c642de03833a3d1d693547d will help.

**Comment by gravitystorm** [comment]
> Sorry @gravitystorm I wasn't necessarily trying to say we should close this... I'm just a bit jaded trying to keep the cache show on the road and finding that every time you fix one machine it moves the problem somewhere else :-(

Oh, I can understand the jadedness, I just felt that having this specific issue open was therefore not going to help solve any of the wider problems. If it was a specific problem with the specific server, then that would be different, but since it's just part of the wider tile serving situation then I was happy just to close it.

Thanks for looking into the situation though!

**Comment by AndreSchwarzer** [comment]
@tomhughes && @gravitystorm Would another server on the same or different provider help? 

BTW I'm the sponsor of keizer 😄 👨‍💻

**Comment by tomhughes** [comment]
Tricky... Germany is a bit of a nightmare, being split across four servers of differing capacities :-(

**Comment by AndreSchwarzer** [comment]
So a "clone" (same capacities) of keizer on cloud.hetzner.de too ?

So it'll be 5 servers of 4 settings :P

**Comment by Firefishy** [comment]
@AndreSchwarzer yes, another server would be greatly appreciated. Best is via email operations AT osmfoundation. Org

**Comment by AndreSchwarzer** [comment]
I am resending my mail from August 08 2019

**Comment by AndreSchwarzer** [comment]
You should have mail
