### ISSUE TITLE
cgimap 0.8.0-dev on dev instance: 4 new GET methods

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/operations#324]
cgimap has 4 new GET methods on master.apis.dev.openstreetmap.org, which could be tested once the Apache rules have been updated accordingly. It's largely based on previous unfinished work by @zerebubuth.

- /api/0.6/node/nnn/relations
- /api/0.6/way/nnn/relations
- /api/0.6/relation/nnn/relations
- /api/0.6/node/nnn/ways

(where _nnn_ is some object id).

See: https://github.com/zerebubuth/openstreetmap-cgimap/pull/166

**Comment by tomhughes** [comment]
Implemented inhttps://github.com/openstreetmap/chef/commit/514aa01f7c3fb627447dd2ac0f049dee640fc8f2.

**Comment by gravitystorm** [comment]
Just on a general point - why?

 I mean, these calls worked fine in the openstreetmap-website codebase, right, so why are they being added to cgimap? Is it so that they can be moved to the read-only database replicas? Or are they causing a significant processing burden in the rails code? Or for some other reason?

**Comment by tomhughes** [comment]
Because the goal is to move the API into cgimap?

**Comment by mmd-osm** [comment]
As I said, @zerebubuth worked on this in 2015-2016 and it was already +80% done. I just resurrected the code and added / fixed the unit tests where needed.

**Comment by mmd-osm** [comment]
By the way, 0.8.0-dev has 3 other endpoints already implemented. I need some more time for reviewing things, so they are not yet included in this round of testing. That's: create/update and close changesets.

**Comment by gravitystorm** [comment]
> Because the goal is to move the API into cgimap?

So ... why do you want to move the API into cgimap?

I can understand why cgimap was initially created, back in 2009, in order to handle the map requests since they were huge and slow and memory hungry and so on. And allowing cgimap to read from the replicas has been very useful too.

But with the intervening 10 years, things have changed, particularly in the rails world (e.g. https://github.com/openstreetmap/openstreetmap-website/issues/2352 ). Most of the "slowness" in the rails code, for example for uploads, is nothing to do with "ruby vs C" and everything to do with how the queries were written (e.g. https://github.com/openstreetmap/openstreetmap-website/issues/1710).

So is "moving everything to cgimap" still a worthwhile goal, in 2019? What benefits does it bring? And what downsides?

**Comment by mmd-osm** [comment]
For the fun of it: this little screencast of a JOSM session highlights what you can already do on a cgimap 0.8.0-dev backend _only_, here on a Raspberry Pi 2 (ARMv7, Raspbian stretch).

Postgres db was initially set up with some schema and user master data. Also, cgimap was added to an existing lighttpd config as fastcgi server.

Not that it's particularly relevant for production, yet it gives you some ideas what you can do with a small dedicated core OSM API engine.

![Peek 2019-08-27 20-11](https://user-images.githubusercontent.com/5842757/63796919-44ef5380-c907-11e9-8c13-5f129de0ba4e.gif)

//cc: @mojodna

**Comment by mmd-osm** [comment]
@tomhughes : I'm wondering if there might be some issue with the automated cgimap update on the dev instance. I pushed some changes to the cgimap master branch a few hours ago that are not yet reflected on the dev instance. Usually, this process takes less than 15-30 minutes.

I renamed a few files in the src/parsers and include/parsers directory recently, and if the build process on  `errol` reuses the previous compilation direction, some stale object files might have caused linker failures. Running `make distclean` could be one option to clean up previous build artifacts before starting a new build.

**Comment by tomhughes** [comment]
Yes the build failed the other day. Sorry I assumed you would fix it...

**Comment by tomhughes** [comment]
Here's the error:

```
---- Begin output of make -j ----
STDOUT: Making all in src
make[1]: Entering directory '/srv/master.apis.dev.openstreetmap.org/cgimap/src'
  CXX      process_request.lo
make[1]: Leaving directory '/srv/master.apis.dev.openstreetmap.org/cgimap/src'
Makefile:982: recipe for target 'all-recursive' failed
STDERR: make[1]: *** No rule to make target 'parsers/exception.cc', needed by 'parsers/exception.lo'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make: *** [all-recursive] Error 1
---- End output of make -j ----
```

**Comment by mmd-osm** [comment]
Thanks! So my assumption seems to be right, that's a left over from a previous build before `exception.cc` was renamed to `exception.cpp`. Travis doesn't have the issue (https://travis-ci.org/zerebubuth/openstreetmap-cgimap/builds/579431722), as they start with a fresh build environment every time, and here the build completes without issue.

Unfortunately, there isn't much I can do from my side, as I cannot clean up the build directory on the server.

**Comment by tomhughes** [comment]
What do I need to cleanup exactly? There appear to be no exception* files and and git status show no local differences...

**Comment by tomhughes** [comment]
Sorry looking at wrong tree, there is exception.cpp but still not sure what to do?

**Comment by mmd-osm** [comment]
Could you try a `make distclean` in the build directory? It should clean up all old artifacts.

**Comment by tomhughes** [comment]
I just blew the whole thing away in the end and let it do a clean build.

**Comment by mmd-osm** [comment]
I think that did it! New version is up and running :+1:
