### ISSUE TITLE
Wiki search not working regression

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/operations#329]
I am not sure if this is the right place to report. I tried to search for "shop=bicycle" in the wiki and the page was ranked very low. See attached screenshot:

![Screenshot 2019-10-04 at 10 33 03](https://user-images.githubusercontent.com/581288/66193416-c5d20580-e692-11e9-97bb-740331da6994.png)

There's the Finnish version and 2 less relevant pages (less usage and less literal similarity with the search term) before the actual hit. I also tried logged out and the result is the same.

**Comment by mmd-osm** [comment]
@Tigerfell: could you take a look at this one? Thanks!

**Comment by Tigerfell** [comment]
@mmd-osm This is on hold for me as long as the partially related PR openstreetmap/chef#257 is not commented. It looks to me like the maintainers do not have the capacity to review, so unfortunately I do not see a point in opening new PRs for now.

**Comment by 1ec5** [comment]
I’m not sure if it’s a regression; search results on the wiki have always been pretty poor, in part because of “pseudo-namespaces” like Key: and Tag: coexisting with actual language namespaces that should really be subpages (“Tag:key=value/fi” rather than “FI:Tag:key=value”). But the result quality has regressed in this case, maybe it has to do with [this change](https://wiki.openstreetmap.org/wiki/Special:Diff/1867839) a few months ago that excludes the language bar from search engine index. That cleaned up search results for language names, but perhaps it may have inadvertently worsened results for “key=value” searches, because the language bar also includes the page name.

Value description pages should still contain “key=value” via [the infobox template](https://wiki.openstreetmap.org/wiki/Template:ValueDescription), but perhaps CirrusSearch is treating the infobox as auxiliary content since it’s in an HTML table. CirrusSearch does offer some options for boosting specific templates ([discussed here](https://wiki.openstreetmap.org/wiki/Talk:Wiki/Archive_6#Proposal:_new_namespace_for_tagging_proposals)), but they’ll require some trial and error.

**Comment by pnorman** [comment]
The specific issues here seem to be gone - searching for shop=bicycle returns Key:shop and Tag:shop=bicycle as the top two results.
