### ISSUE TITLE
Using render servers for limited regions

### ISSUE THREAD

**Issue by danfai** [openstreetmap/operations#395]
While the servers itself are very powerfull, none of those can cache the hole database.
In europe we have at least two servers with low latency to many of the caches.
We could prefer one of those render servers based on the tile numbers. 
E.g the french server renders everything western europe and North/South America and Amsterdam renders everything east of that border.

**Comment by tomhughes** [comment]
We do essentially do that by directing particular caches to particular render servers - because caches tend to be asked for tiles from the countries they are serving that also controls what tiles a render server is typically asked for.

Splitting by region creates considerable additional complications in arranging fallback when a render server is unavailable and also makes debugging issues much harder so there really needs to be a compelling reason to do it and as we currently have plenty of render capacity I'm not convinced it's a good idea at the moment.

**Comment by danfai** [comment]
While I agree that in the current situation _most likely_ the rendering is primarily in some geographical constraints, there are more than likely users visiting other regions.

I definitely do not want to have limited databases on the render servers.
Regarding fallback, right now the caches need to fall back to other render servers as well. There would be no change, simply mark as down and continue with other one(s), which then obviously has increased load, similar to now.

Since my assumption was the whole tile CDN including render servers is at capacity (req/s), I'm going to close this one.
