### ISSUE TITLE
tilecache: Use redirects instead of passthrough for tiles

### ISSUE THREAD

**Issue by danfai** [openstreetmap/operations#399]
If there is a lot of bandwidth between multiple caches (like during the recent misconfiguration) and/or bandwidth is a factor to take care of:

For tiles that do not need to be cached by the tilecache receiving the requests, the tilecache could return the address of the tilecache that has the tile on disk.
HTTP provides this with 301 or 302 Moved temporarily/permanently. Since all tilecaches have their own DNS names, we might be able to return the hostname with the 301/302.

(possible) disadvantages:
1. The CDN becomes more visible to the clients.
2. The client may need to do additional DNS and HTTP request increasing the loading time/latency.

To determine the necessity to reduce this problem we need additional statistics for traffic between tilecaches.
Could be used in combination with https://github.com/openstreetmap/operations/issues/398

**Comment by tomhughes** [comment]
This is an absolutely terrible idea and I'm afraid I'm going to reject it outright - it would mean that any change to the tile cache network as caches go up and down would need to be propagated to all tile caches so that they could avoid redirecting to a cache that was down.

In addition to that it requires every cache to know what every other cache has available in order to know what to redirect to - given you are presumably proposing to have every cache keep an up to date database of who was what that presumably means polling caches with HTCP or something to locate a copy. Once you've done that what exactly is the advantage or redirecting over just returning it?

In addition caching peering in squid (assuming this has to be done there - not sure if nginx could do this?) is a shit show which is in large part why it was disabled.

**Comment by danfai** [comment]
> In addition to that it requires every cache to know what every other cache has available in order to know what to redirect to
not necessarily. My idea would be to request the tile from other tilecaches and if they detect a requests origin from another tilecache they return the redirect. Therefore the redirect can be passed through the client. It is simply a matter of trading latency with bytes, since a redirect is much smaller than the tile itself but loading may increase.

> In addition caching peering in squid (assuming this has to be done there - not sure if nginx could do this?) is a shit show which is in large part why it was disabled.
Above should be possible with nginx (or probably most http servers).

**Comment by tomhughes** [comment]
What I don't understand is what all this additional complication is supposed to achieve - why do you want to return a redirect?

**Comment by danfai** [comment]
With the current setup it probably wont change much at all, since I believe there are not many requests propagated from one tilecache to another one. In cases where there might be more (eg squid not reachable or render servers high load) the following happens:
client asks for tile at cache1 -> cache1 may not have it, asks cache2 -> cache2 has it, returns tile to cache1 -> cache1 returns tile to client and maybe adds to storage.
So cache1 has the tile added as bandwidth in both directions (incoming + outgoing) and perhaps added to its local storage.
Both might be reduced.

**Comment by tomhughes** [comment]
Network bandwidth is rarely the limiting factor on our caches - the limiting factor is typically some combination of CPU and/or disk I/O limits.
