### ISSUE TITLE
Add a Logstash (ELK stack) server

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#40]
Brain dump...

https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-4-on-ubuntu-14-04

deb http://packages.elasticsearch.org/elasticsearch/1.6/debian stable main
deb http://packages.elasticsearch.org/logstash/1.4/debian stable main
deb http://packages.elasticsearch.org/logstashforwarder/debian stable main
deb http://packages.elasticsearch.org/curator/3/debian stable main
kibana getting an debian package soon https://github.com/elastic/kibana/pull/3212

**Comment by tomhughes** [comment]
Yeah I had a look after the meeting on Monday and it all looks a lot easier now, with actual packages rather than having to hand install piles of java.

I'm a bit concerned about how much resource it might need, given @gravitystorm was talking about having three machines just to run elasticsearch!

Also need to decide whether to use full logstash on the clients or just the forwarder, as the forwarder is supposed to be going away at some point so that might not be a very forward looking solution.

Main issue will be figuring out how to actually ingest the logs though, especially the multiline rails logs, as I'm not sure the logstash multiline filter is powerful enough to manage them.

**Comment by tomhughes** [comment]
Oh, and what's kibana? Never even heard of that...

**Comment by Firefishy** [comment]
kibana is for visualising or analysing the data.
colleague also recommends https://github.com/lmenezes/elasticsearch-kopf

**Comment by tomhughes** [comment]
My main goal in the first instance is just to be able to search the web logs and get a complete set of related apache and rails/cgimap (both multiline) log entries grouped together.

**Comment by gravitystorm** [comment]
> given @gravitystorm was talking about having three machines just to run elasticsearch

That's just to make some massive queries run faster, and to store plenty of historical logs. For a long time I ran with just one machine, it works fine but obviously has no replication of the logs.

**Comment by tomhughes** [comment]
So I've done a bunch of preliminary work and am pretty much at the point where we should be able to ingest the logs from apache and rails on all six machines and link log entries for the same request together.

What I need to decide now is what the actual logstash architecture should look like...

Upstreams preferred design seems to be to run logstash on each machine to do log parsing and then forward parsed entries to the main server, probably via something like redis to act as a buffer. The down side is that it requires installing a JVM on each machine as logstash is written in java.

The alternative is to use the logstash forwarder, which is small and not written in java, but which they freely admit will go away some day. That doesn't do any parsing and would just forward to a central server.

**Comment by Firefishy** [comment]
Running a full persistant JVM + logstash proper on each endpoint machine seems very unwieldy to me.

In the unlikely event that logstash-forwarder goes away completely, there will likely be something to replace it.

**Comment by tomhughes** [comment]
So this has been up and running on ironbelly for some months and has proved useful on occasion but currently we're quite limited by disk space etc so we need to be thinking about more permanent hardware.

**Comment by Firefishy** [comment]
How much disk space would be ideal?

**Comment by tomhughes** [comment]
Well currently we are using 37Gb for apache+rails logs for the main site, but are only able to keep about 2-3 days worth.

Ideally we would be able to keep a bit more than that, and add cgimap at least.

Beyond that, well it depends if there's anything else people want to log into it.

**Comment by zerebubuth** [comment]
What are the CPU requirements like? From [munin](http://munin.osm.org/openstreetmap/ironbelly.openstreetmap/cpu.html) it doesn't look like more than 2 CPUs are ever used (apart from weekly planet dump spikes). So it sounds like this is something that could run on a DL360, if it had relatively large, but still spinning rust, disk?

**Comment by tomhughes** [comment]
Well there are two questions there - the ongoing CPU usage to process and index incoming log records, and the usage to run queries.

The first is hopefully not very high, and the second is sporadic and can probably go as high as you like depending on the queries.

It's probably best to wait until @gravitystorm is back and discuss it with him as he has much more experience with it than me.

**Comment by kosfar** [comment]
Hello osm-ops,
I am not sure about the status of the project, but I would like to offer some insight on the questions that arose on previous posts based on my experience. Running single-node elasticsearch cluster is not generally recommended in production due to heap size restrictions [1], availability concerns, performance degradation due to mangling master and data roles and limited use of distributed natural strengths of ES.

Elasticsearch is more of a memory-hungry, than CPU-hungry beast. When ES starts choking on CPU, then something is wrong with its configuration or architecture. On the other hand Logstash is more of a CPU-dependent software especially when you start using complex regexes and groks.

You may also want to check HQ [4] for better ES monitoring.

Regarding the shipper layer, I wouldn't choose neither for logstash nor for logstash-forwarder. Log-courier is a fork of LSF and is much more actively developed and maintained + has a lot of useful features that LSF is missing for years [2]. There is also this cool new thing called Beats, which I haven't tried but looks promising.

If there is interest for the project, I would be glad to help with the stack when new hardware comes into play @tomhughes !

[1] https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html#compressed_oops
[2] https://github.com/driskell/log-courier
[3] https://www.elastic.co/products/beats
[4] https://github.com/royrusso/elasticsearch-HQ

**Comment by pnorman** [comment]
If we're running it is there anything left for this issue?

**Comment by tomhughes** [comment]
I need to get Kibana working again but no, not really.
