### ISSUE TITLE
tilecache: More insight/statistics

### ISSUE THREAD

**Issue by danfai** [openstreetmap/operations#400]
To get better insight for improving performance, statistics are necessary.

There are many variables in nginx usable for log_format. Of course most of them are probably useless for logging.
Useful ones may include $upstream_cache_status and $upstream_addr. ( http://nginx.org/en/docs/http/ngx_http_upstream_module.html#variables or http://nginx.org/en/docs/varindex.html )

- [ ] Maybe this munin plugin would do the same thing as the squid miss/hit rate, with the above variables in the log:
https://github.com/munin-monitoring/contrib/blob/master/plugins/nginx/nginx-cache-hit-rate

To get the path each tile has travelled, either log the number of caches involved in each request (based on headers, e.g. number of X-Cache... or custom header, where each tilecache adds one character (maybe unique) to the header)

For a fast analysis of the requests between tilecaches, the logs can be searched for the IP addresses of other tilecaches. (possibly helpful for https://github.com/openstreetmap/operations/issues/399)
The problem will be that those values can only be aggregated by sysadmins and would not be in munin. Additionally using munin graphs adds the advantage of long term analysis for the above ideas. (E.g. historical statistics are available and therefore one can see, that January 2020 nginx has a lot more requests because of some change in git/chef)
https://osm.danfai.de/munin-tile/target/request-year.html

I am currently working on understanding the typical tile usage based on the access logs from tilecaches (https://planet.openstreetmap.org/tile_logs/). On https://osm.danfai.de/tileaccess a heatmap for requests on current zoomlevel+9. Data is aggregated by calendar week (cw14 and cw15 currently). Each pixel represents one tile, depending on the amount of requests the pixel gets more white.
This is work in progress, I want to extend it to combine all zoomlevels and hope to find some more insight for possible splitting of region for render resources. Comments are welcome :)

- [ ] Sadly those tile_logs are from squid, can/should we get aggregate ones for nginx?                                

For a side by side view of some munin graphs of tilecaches, I created https://osm.danfai.de/munin-tile/target . Maybe it helps someone else.

**Comment by tomhughes** [comment]
Any munin plugin that works by analysing the logs is likely unworkable due to the volume of data it would need to process in more or less real time.

In addition we are not in fact currently logging from nginx at all, although we do want to change that.

The history is that we disabled logging in nginx because we were running out of disk space on some caches and the nginx logs were just duplicating the squid logs leading to extra I/O to create them, extra disk space to store them and extra CPU time to compress them each day for something that was of limited use.

What has changed is that nginx now does it's own caching so they are not duplicative.

The obvious answer is to reverse the policy and enable nginx logging while disabling squid logging - my only concern is that will make it hard to debug issues in squid if we can't see the squid status for responses but it might be possible to log that from nginx instead.

**Comment by pnorman** [comment]
As we are moving to a commercial CDN this issue is now moot.
