### ISSUE TITLE
Deprecate trac

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#416]
Trac has been removed from Ubuntu 20.04. We should finally deprecate trac and direct people at the appropriate project-specific trackers. 

Looking at https://trac.openstreetmap.org/wiki/OsmComponentReports every project except utils has either moved or is dead.

Because trac has connections with SVN, I think we should at the same time take initial steps in deprecating that too.

I propose the following as a timeline
- Immediate: Send out an email that we will be deprecating trac and not creating SVN accounts unless necessary for moving projects out of SVN.
- Immediate: Update the trac front page to say all projects have moved, trac is being deprecated, and giving alternative locations
- Late June: Put trac read-only and stop creating new SVN accounts

The archivist in me would like some way to keep serving read-only historical trac content, ideally as static pages. I don't know how possible this is.

**Comment by hbogner** [comment]
Regarding archive, we used wget with some extra options to create a static archive of an old portal. Can this aproach help with trac?

**Comment by gravitystorm** [comment]
>     * Late June: Put trac read-only and stop creating new SVN accounts

Just to note that I'm still working my way through the trac tickets for openstreetmap-website, and either closing them with an explanation for the original reporter, or fixing them, or transferring them to github as appropriate. I certainly won't have finished this by June, based on progress to date. If it's made read-only before I finish then I'll continue the process, but won't be able to update the original tickets with links or explanations.

**Comment by mmd-osm** [comment]
>  I certainly won't have finished this by June

If it takes you too much time, we should think about splitting up the work. There's no reason why should do this on your own. I'm closing a few API ones right now, as I did in the past already. A lot of the issues  don't apply anymore, cannot be reproduced, etc.

**Comment by tomhughes** [comment]
The machine running trac is likely to be fairly far down the list of things to upgrade as there are other services on there which have issues that need resolving...

**Comment by pnorman** [comment]
> Just to note that I'm still working my way through the trac tickets for openstreetmap-website, and either closing them with an explanation for the original reporter, or fixing them, or transferring them to github as appropriate. I certainly won't have finished this by June, based on progress to date.

That's a good reason to push the date out.

> The machine running trac is likely to be fairly far down the list of things to upgrade as there are other services on there which have issues that need resolving...

Ya, but I wanted to allow time between read-only and shutting it down or moving it to a container, as well as time between that and the OS upgrade.

**Comment by gravitystorm** [comment]
> If it takes you too much time, we should think about splitting up the work. 

I'm always happy to have help! Working through old tickets is hard and boring work though, so I understand if people prefer to work on other things.

> A lot of the issues don't apply anymore, cannot be reproduced, etc.

I think the remaining ~70 issues are getting harder to deal with, since I've picked of ~80 of the easier ones to deal with already :-) There are lots of judgement calls and semi-arbitrary decisions to make.

> That's a good reason to push the date out.

I appreciate having more time, but at the same time, I don't want to delay any of your plans unnecessarily (or for a long duration). When I'm working on these tickets I only get through about 5 - 10 tickets at a time, so it could take a while to finish them off. Maybe if it ends up where this is the only thing you are waiting for I can just do a copy+paste of the few remaining tickets into Github and triage them later.

**Comment by openbrian** [comment]
This ticket saddens me.  I like Trac.  They're finally getting their act together and upgrading to Python 3.

**Comment by mmd-osm** [comment]
> I think the remaining ~70 issues are getting harder to deal with, since I've picked of ~80 of the easier ones to deal with already :-) There are lots of judgement calls and semi-arbitrary decisions to make.

Down to 52. There are quite a number of issues that are either of little significance these days, cannot be reproduced anymore due to changes during the last 9 years,, have duplicates on Github. 
As a rule of thumb: really important topics would have re-surfaced on Github anyway.

There are a few clusters of topics, like GPX, or "friends nearby", and quite a bit of noise.

It would be good if some volunteers out there could do a bit of pre-qualification:
* do you understand what the issue is about? 
* is this issue still relevant today?
* are there existing issues on Github covering the same topic?

**Comment by mvl22** [comment]
We used this trac2github script when moving from Trac to Github, and it worked well.

https://github.com/bflorat/trac2github

We moved across everything as faithfully as possible, with no loss: tickets, comments, milestones, tags, authors names, status, wiki pages.

We treated the conversion as a technical change, with the cleaning up and closing of tickets to be done as a separate task afterwards in Github, as our objective was primarily to shut down SVN/Trac.

**Comment by mmd-osm** [comment]
The idea is interesting. However, I wouldn’t post those to the osm website repo (we have plenty of issues there already), but create a separate repo like legacy-trac-issues. If some of them turn out to be useful, we can still move them to the main repo.
Main issue I see is that unlike in trac where basically everyone can do whatever they like, we only have very few people on GitHub that can close issues. Here where we’ll definitely hit a bottleneck, as scaling to many people just doesn’t work without assigning them to the repo as collaborators.

**Comment by gravitystorm** [comment]
> Down to 51.

Thanks for your help @mmd-osm ! I really appreciate it, and I know first-hand the effort involved.

I'm not particularly worried about transferring tickets from trac to github (e.g. in another legacy-tickets repo), the effort involved is not worthwhile in my opinion. We should just deal with whichever tickets we can in the meantime, particularly while they are still linked to the original reporter who might be interested in the response.

As you say, most of the important topics will come up again anyway, so nothing needs 100% continuity in tracking.

All this only applies to the website, I don't have any opinions on the nominatim or potlatch2 tickets.

**Comment by mmd-osm** [comment]
According to https://wiki.osmfoundation.org/wiki/Operations/Minutes/2020-05-22, Trac archiving [is] necessary. I don't know what exactly that means and there's little detail in those minutes. I hope nobody is spending extended amounts of time/money on those old issues, they're hardly worth it...

44 still left to go.

**Comment by tomhughes** [comment]
I hadn't seen those minutes before but I don't recall that being decided.

**Comment by pnorman** [comment]
Trac deprecation announced: https://lists.openstreetmap.org/pipermail/dev/2020-July/030958.html

We will be switching Trac to read-only at the end of July.

**Comment by mmd-osm** [comment]
> We will be switching Trac to read-only at the end of July.

DId this happen, or was it postponed, maybe? I still seem to be able to change old tickets.

**Comment by simon04** [comment]
@JOSM ticket: https://josm.openstreetmap.de/ticket/19509

JOSM mailing list: https://lists.openstreetmap.org/pipermail/josm-dev/2020-August/008316.html

JOSM now uses a hosted copy of OSM SVN at https://josm.openstreetmap.de/osmsvn/ (UI https://josm.openstreetmap.de/log/osm)

**Comment by mmd-osm** [comment]
Found this one on https://wiki.osgeo.org/wiki/Trac#Making_Trac_Read-Only:

# _Making Trac Read-Only_

_It appears the usual way of making Trac read-only is to remove all permissions on the "authenticated" group in the Admin/Permissions dialog. This will remove the authenticated group and then only those with special admin priviledges can edit the wiki, create tickets, etc._

**Comment by tomhughes** [comment]
I have now removed all permissions from the `authenticated` group so trac is now readonly for everybody except me.

**Comment by Firefishy** [comment]
Haven't found an easy way to create static exports of the old tickets. Trac is now holder back some upgrades.

**Comment by HolgerJeromin** [comment]
You could use wget or httrack. But the result is quite ugly (multiple duplicate files)

**Comment by mvl22** [comment]
See my suggestion above of using trac2github, which could be adapted to output HTML files or a CSV, by skipping the final Github API push phase.

https://github.com/mvl22/trac2github/blob/master/trac2github.php

Ultimately trac is a database that can be queried in SQL.

**Comment by tomhughes** [comment]
So that does work, at least with a little bit of hacking to avoid triggering github's API rate limits.

Everything winds up owned by one user with the original author mentioned in the text - in principle you can map users but that requires having a token for each person's github account.

One problem with the result is that I don't think you can set issues to read-only on a github repo - you can disable them but then they vanish. I guess we could script something against the API to lock them all and add an issue template to discourage new reports.

**Comment by lonvia** [comment]
I have been spammed a little bit with dozens of email notifications from your experiments, @tomhughes, because of the mentions. Is that something that can be disabled before an import?

**Comment by mvl22** [comment]
Yes, there is support in that script as you say for mapping users if you have their tokens. (We had a relatively small number of people, so wasn’t too bad in our case.)

**Comment by tomhughes** [comment]
I'm surprised @lonvia got notifications because as far as I know the only account linked to any of the tickets is mine - do you have an example of a ticket that caused a notification?

There are email address in many of the comments just because many of the trac usernames are email address - that is why I have made the repo private now. I believe there is an option to obfuscate them if we do it for real.

**Comment by lonvia** [comment]
So it's less spamming than I feared. I got 25 notifications but they only refer to a total of four tickets:

https://github.com/tomhughes/trac-tickets/issues/5119, https://github.com/tomhughes/trac-tickets/issues/5420, https://github.com/tomhughes/trac-tickets/issues/5277, https://github.com/tomhughes/trac-tickets/issues/5178, https://github.com/tomhughes/trac-tickets/issues/5420

**Comment by tomhughes** [comment]
Right, so it looks like it happened where somebody used `@user` in a trac comment to refer to somebody and there is a matching username on github.

**Comment by pnorman** [comment]
Done in https://github.com/openstreetmap/chef/commit/c22837a672db48d4439247608c9f3ebaf2530e0f
