### ISSUE TITLE
Missing renderd munin graphs on pyrene

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#425]
I was trying to find out why I see no tiles this morning, and came across missing munin graphs on pyrene. Most, but not all, renderd graphs appear to have stopped working three weeks ago.

![image](https://user-images.githubusercontent.com/360803/84013232-f03e3600-a978-11ea-88a7-0b78a503f1f7.png)

**Comment by tomhughes** [comment]
Missing graphs like that (it's not just rendered) usually just means that some plugin is very slow and the timeout is hit meaning graphs from subsequent plugins don't get any data.

**Comment by tomhughes** [comment]
The offender was actually the mod_tile plugins which were timing out connecting to apache because, for some reason, it was ignoring connection attempts on the IPv6 loopback address (the IPv4 address worked) and the mod_tile plugins use http://localhost/ to fetch statistics.

Restarting apache seems to have fixed it.

**Comment by gravitystorm** [comment]
> I'm not sure how that is relevant to you not seeing any tiles

The relevance is that I like to debug what's going on, to try to help suggest where the bottlenecks are. From here in Poland, tile.openstreetmap.org was showing pyrene as the render server. :shrug: 

> Restarting apache seems to have fixed it.

Thanks!
