### ISSUE TITLE
Replace failing DB disk in Katla

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#43]
Disk in Katla is failing. Disk is sill under supplier warranty.
---
Device: /dev/sg0 [megaraid_disk_16], SMART Failure: DATA CHANNEL IMPENDING FAILURE DATA ERROR RATE TOO HIGH

Device info:
[SEAGATE  ST900MM0026      0003], lu id: 0x5000c5005e8fe503, S/N: S0N01WTZ00009320PEKN, 900 GB

**Comment by zerebubuth** [comment]
Disk replaced & failing one returned to supplier.

**Comment by Firefishy** [comment]
Awesome. Thanks.

**Comment by Firefishy** [comment]
I think the wrong disk was replaced. This was just logged. Can you compare serial?

Device: /dev/sg0 [megaraid_disk_16], Read SMART Self-Test Log Failed

Device info:
[SEAGATE  ST900MM0026      0003], lu id: 0x5000c5005e8fe503, S/N: S0N01WTZ00009320PEKN, 900 GB

**Comment by zerebubuth** [comment]
The new disk in slot 26:8 became the new hot spare and is spun down at the
moment, which might account for why the SMART values can't be read. The
array pulled in one of the previous hot spares in 26:16, which seems to be
okay.

I checked the results of a MegaCli poll of SMART failures and it didn't
turn up any, so I reckon it's most likely due to the new disk becoming a
hot spare and being spun down.

Let me know if that doesn't make sense and I'll dig a bit deeper. I'm
pretty sure I pulled the right disk, but I could have been mistaken.

**Comment by zerebubuth** [comment]
There seem to be two issues here:

1. `megaraid_disk_16` no longer exists. The new disk was assigned ID 28 instead.
2. The controller is configured to spin unused (hotspare, unconfigured) disks down, at which point they won't respond to any commands and `smartctl` reports that it doesn't support SMART.

Manually unconfiguring the new disk in order to spin it up shows that the serial number is different (ends in ...BN9D). A short SMART test passes, a long one fails because the controller spins the disk down before the long test finishes.

It seems that anything that is monitoring the currently-up disks would need to something like `MegaCli64 -pdList -a0 | grep "^\(Device Id\|Firmware state\):" | grep -B 1 "Spun Up" | grep "Device Id" | awk '{print $3;}'` to get the list of IDs which will respond to a SMART status request.
