### ISSUE TITLE
Odin not updating tiles?

### ISSUE THREAD

**Issue by nrenner** [openstreetmap/operations#440]
There are multiple reports in the German forum that changes are not appearing on the map.

First examples are starting Friday, some later changes:

- https://www.openstreetmap.org/way/825733468#map=18/49.97857/8.41502 (Monday)
  - https://odin.openstreetmap.org/18/137199/88929.png
- https://www.openstreetmap.org/way/826230089#map=19/50.82192/13.44161 (Tuesday)
  - https://odin.openstreetmap.org/17/70429/43982.png
- https://www.openstreetmap.org/way/827070612#map=19/48.58694/8.85951 (10 minutes)
  - https://odin.openstreetmap.org/19/275046/180965.png

**Comment by tomhughes** [comment]
There is no replication lag so it should be fine - most likely you're just seeing cached tiles that haven't invalidated. The invalidation algorithm is only heuristic and some type of change will not cause invalidation.

Unless you can identify a systemic problem somehow it's not really practical to investigate individual tiles like this - the work involved is significant and we have limited manpower.

**Comment by tomhughes** [comment]
All these appear to be fine after a rerender is force so it's just tiles that didn't get invalidated for some reason.

**Comment by tomhughes** [comment]
I managed to identify an issue in the expiry script caused by the update to Ubuntu 20.04 on the tile servers that I have fixed in https://github.com/openstreetmap/chef/commit/fb3022d7a7139bed87a118e7f7928681c886b1fd.

Pending changes are now processing, but some will have been lost as they expire from the queue after a while - it will self correct when the style is next changed or if the same area is touched again.

**Comment by nrenner** [comment]
Thanks for the fix and explanation, I passed it on.
