### ISSUE TITLE
Extend prometheus metric retention

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#484]
Currently we only retain the default 15 days of metrics with Prometheus. To meet the planning use-cases that Munin can, we need to retain at least a year's worth of data.

The [Prometheus storage documentation](https://prometheus.io/docs/prometheus/latest/storage/) states
> Note that a limitation of local storage is that it is not clustered or replicated. Thus, it is not arbitrarily scalable or durable in the face of drive or node outages and should be managed like any other single node database. The use of RAID is suggested for storage availability, and snapshots are recommended for backups. With proper architecture, it is possible to retain years of data in local storage.

The documentation recommend remote storage integration for scalability and long-term storage, but it's not clear to me if we're beyond what a single node can handle.

**Comment by tomhughes** [comment]
As I said on the call a few weeks ago Prometheus itself is not really intended for storing long term data - aside from anything else the two weeks we are storing at the moment uses 60Gb or so.

There are I believe systems that can take the data and do longer term aggregation in PostgreSQL/TimescaleDB.

**Comment by tomhughes** [comment]
The thing that I saw recently that drew my attention to this was https://blog.timescale.com/blog/promscale-analytical-platform-long-term-store-for-prometheus-combined-sql-promql-postgresql/ from the TimescaleDB people.

**Comment by tomhughes** [comment]
I'm going to investigate using Promscale...

**Comment by grinapo** [comment]
Let me chime in. 

I am using [VictoriaMetrics](https://docs.victoriametrics.com/) for more than 2 years now as a backend for prometheus (plug-in) compatible data storage. I am storing more than 150 billion data points on a _single_ server, and retrieval times for hot data in tens of millisec range, and cold data was just retrieved in 40 seconds (two years query over about 130 billion data points). The storage used is 32 GB (that is about 3 _bits_ per datapoints on the avereage).

The system is open source, and fully prometheus compatible, apart from alertmanager (but integrates well with prometheus' one), but contains very useful extensions to the general promQL feature set, including simple mass configuration. It also always have been flawlessly upgraded, was stable and reliable. It is written in Golang, if that mattered. The system can generate snapshots and consistent backups, including incremental ones.

V.M. also contains clustered versions of all its subsystems (including vmagent which retrieves and the backend which stores the data).

Apart from the open source version there is an "enterprise" version, which also contains a very useful feature called _downsampling_, which bascially use an admin-selected function to aggregate given time ranges of the series. With this it is pretty simple to create a hot and a cold storage, former using 15 seconds sample rate and the latter downsampled to 10 minutes.

I am actually not even using enterprise for downsampling but use the "recording" feature of vmalert, which continuously streams the 10 minute aggregated data stream into the cold storage, while my hot storage purges at 14 days. My cold retention is 5 years currently (but I'm obviously not even close to that).

If you need any more ops info feel free to ask. I am not related or involved with the V.M. team, though I've been conversating with them and they always have been swift and helpful regaring any questions about the system (they're mainly available through Telegram). It turned out to be an excellent system for a maniacal statistics fan.

**Comment by tomhughes** [comment]
It's probably unfortunate that we went the promscale route, largely on a misunderstanding on my part, but it does seem to be working reliably now so I'm not especially keen to try and change direction although better performance and downsampling support does sound good.

Just to understand you're not using prometheus internal storage at all but instead remote write to a hot version of VM and then from that (via downsampling) to a cold version of VM?

Can you also clarify what you mean about not working with alertmanager but integrating with prometheus alerts? Aren't those the same thing? Do you mean that it doesn't work with grafana alerts?

**Comment by grinapo** [comment]
> It's probably unfortunate that we went the promscale route, largely on a misunderstanding on my part, but it does seem to be working reliably now so I'm not especially keen to try and change direction although better performance and downsampling support does sound good.

Well if it works there's no need to change; I cannot comment on promscale since I am not familar with it.

I believe it is also possible to use recording rules to actually aggregate hot prometheus storage into a cold VM backend (though it would require a dataset selection in the dashboards, on my dashboards there is always a dataset selector variable at the top; like selecting "Hot Prometheus" or "Cold VM" as data source, probably also changing sampling-rate size from 15s to 10m).

Also it is pretty simple to test, since it's a single-binary program using the same config as prometheus. The only requirement is that the test server have to be able to connect to the metrics clients (apart from the disk space and other local resources required; it is definitely happier when there's enough memory, the specific amount based on the size of the data, for me it is 600MB for cold and 2-4 GB for hot db). 

(I can pull one up in an hour, in fact I did it recently; if anyone wants to look.)

> Just to understand you're not using prometheus internal storage at all but instead remote write to a hot version of VM and then from that (via downsampling) to a cold version of VM?

I am not using prometheus storage (but since VM uses standard prometheus API [among graphite and influx] I am pretty sure it can use prom storage for siphoning out data, though I never have tried that). 

My system is collecting data (15 s resolution usually) using `vmagent`, which push the hot data into VM backend. Then a lot of `vmalert` recording rules create averages (mean) over 10 minutes and _record_ it into cold storage, a separate instance of VM backend. (The cold storage requires lot less resources due to almost no queries.)

> Can you also clarify what you mean about not working with alertmanager but integrating with prometheus alerts? Aren't those the same thing? Do you mean that it doesn't work with grafana alerts?

VM is actually 7 binaries and that's all, not a complex distro. Out of those the main point of interests:
- `vmagent` which connects to clients (apart from prometheus various different protocols supported), retrieves the metrics (either parallel or not), does relabeling, churn control then load the data into one or multiple backends.
- `victoriametrics` is the backend, supporting prometheus read and write api (as well as graphite and influx ingest)
- `vmalert` is the alert _control_ system which evaluates expressions and generate alerts on them, and send the alerts to an **alertmanager compatible interface**; since VM does not have an alert_manager_ people simply use prometheus Alertmanager component for aggregating alerts, handle dependencies and actually send out the alerts
- `vmbackup` and `vmrestore` handles snapshots and backups

The other binaries and for various authentication, cluster handling and eterprise features (like anomaly detection). I am using `vmalert` with prometheus `alertmanager` (not very actively right now, since alerts are already done by a separate system).

VM is integrated with Grafana but I think grafana data source actually uses _Alermanager_ component from prometheus (which is fed by `vmalert`). [This reminds me to actually finish my integration. ;-)] It works out of the box with the same (prometheus style) configuration which VM also uses.

**Comment by tomhughes** [comment]
Oh so you're actually using prometheus at all, you're using vmalert to query prometheus exporters. That would be a really big change for us....

**Comment by grinapo** [comment]
The only difference is the backend I guess. VM uses the same config files.

**Comment by pnorman** [comment]
Based on discussion in #810 we went with extending prometheus retention to about 1.5 years in https://github.com/openstreetmap/chef/commit/2ca02ae7c0d53545b1804846ce356fd83cebd99f

**Comment by grischard** [comment]
@grinapo thank you! We'll see how using pure promotheus works, and come back to this if it fails.
