### ISSUE TITLE
DKIM and subject/body modification in ML

### ISSUE THREAD

**Issue by andrzej-r** [openstreetmap/operations#490]
Would it be possible to disable adding the name of the mailing list to subject header and to the message body?

I do realize this is a long standing tradition but these content modifications break DKIM signatures and by extension DMARC. While running DMARC with p=none is still an option (neglecting the inconvenience of all the reports being sent back), DKIM is now much required by many large email providers.

Ideally, the mailing list server would re-sign the outbound messages but this could be too large of a change to ask for.

**Comment by tomhughes** [comment]
That's an option that is available to each mailing list owner, not something we can control globally.

I very much doubt that it will be enough to stop DKIM breaking anyway - there is no way to run a mailing list that completely avoids making changes to messages which is why mailing lists and hard DKIM enforcement as essentially incompatible.

**Comment by tomhughes** [comment]
In any case we rewrite the From header if the domain has a DMARC policy that enforces DKIM checks so that the from address is an openstreetmap.org address and the DKIM signature for that address (which is the one that should be enforced) should be correct.

The original signature is still present and won't pass as you say, but as it's not for the domain of the apparent from address the DMARC policy for that domain shouldn't be enforced.
