### ISSUE TITLE
Fix yevaud performance

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#5]
The performance of yevaud is (relative to orm) shocking - orm is a bit more powerful but it is doing like eight times more tiles than yevaud.

Things to look at:

- [ ] Replace RAID controller
- [ ] Move SSD to separate controller
- [ ] Increase memory

**Comment by zerebubuth** [comment]
Upgrading all the RAM in yevaud (i.e: to 96GB) would be about £1k. Replacing the current RAID controller with an LSI MegaRAID SAS 9361-8i + cachevault module would be about £820. Is it worth just going ahead with both of these?

**Comment by tomhughes** [comment]
Current proposal from @Firefishy is some or all of:

* Replace database disk with 2 x Samsung 850 Pro 1Tb (though is more for #6 than for performance) [£480 each]
* Add http://www.span.com/product/LSI-Logic-SAS-SATA-Controller-SAS9300-8I-Kit-LSI00345-SAS-SATA-12Gbit-8-Port-Two-x4-Internal-SFF8643-PCI-Express-v3-0-x8-Non-RAID~41423 for the database disks (onboard controller is too slow for above disks) [£316]
* Replace current Areca RAID card with http://www.span.com/product/Areca-SAS-RAID-Controller-ARC-1883i-SAS-SATA-12Gbit-8-Port-Dual-Core-Two-x4-Internal-SFF8643-PCI-Express-x8-v3-0-RAID-0-1-5-6~42314 for the tile disks [£517.20]
* Optionally upgrade memory to 96Gb [£943.13]

**Comment by zerebubuth** [comment]
From meeting: consensus is to buy single Samsung 850 Pro 1TBs for yevaud & orm, a controller for yevaud to drive the SSD, and upgrade the memory in yevaud to 96GB.

**Comment by zerebubuth** [comment]
The new SSD and controller are installed in yevaud, but for some reason the controller hasn't picked up the SSD at all. The controller itself seems to be working fine, and be fully supported, so it's likely that the issue lies in the cabling, power or SSD itself. This will have to be debugged on another visit.

**Comment by tomhughes** [comment]
The SSD is now installed and working and definitely outperforms the old one!

I suspect we probably still need to look at doing something with the tile disks though.

**Comment by zerebubuth** [comment]
A couple of weeks ago, the additional memory was installed in yevaud, taking it up to 96GB. This seems to have improved some I/O service times, but not drastically increased the render rate or Apache throughput.

After the SSD, the yevaud/orm split is looking better than before, but still is about 70% orm & 30% yevaud. Do we think that something needs to be done about the tile disks? Or is the work split more likely to be due to which caches are configured to parent to each of yevaud or orm?

![apache_accesses-year](https://cloud.githubusercontent.com/assets/271360/7534950/ba2378ec-f577-11e4-85c9-581b8a33dc80.png)

**Comment by tomhughes** [comment]
Oh the work split is deliberate and can be changed. I plan to revisit it once orm has been been upgraded to Ubuntu 14.04 so that the software stacks are comparable.

**Comment by tomhughes** [comment]
For the record 70/30 is exactly the target work split currently - we have orm configured with a target bandwidth of 700Mbit/s and yevaud at 300Mbit/s.

**Comment by zerebubuth** [comment]
Looks like orm/yevaud are now on a 60/40 split? Are we happy enough with yevaud's performance after the upgrade?

![apache_accesses-year 1](https://cloud.githubusercontent.com/assets/271360/8279980/d9ebcf5e-18d0-11e5-8c43-7a6b99752f07.png)

**Comment by tomhughes** [comment]
Yes, they're on 60/40 though I'm considering going even further, to 50/50...

Yes I think performance is probably OK now, so I'll close this.
