### ISSUE TITLE
Grant "autoconfirmed" privileges to all board wiki users

### ISSUE THREAD

**Issue by tordanik** [openstreetmap/operations#517]
It is sometimes inconvenient that recently elected board members are unable to perform some actions on the board wiki (board.osmfoundation.org) until they have performed enough edits to gain the user rights associated with "autoconfirmed" status. This is especially true for the permission to upload files. It would probably be best to grant all permissions currently limited to autoconfirmed users to all users upon registration of the account. Board wiki accounts are only handed to select people, so I do not expect much risk of abuse.

The same configuration change could potentially be useful for the OSMF wiki as well.

**Comment by tomhughes** [comment]
Does this actually require a code change? or is it something a wiki admin can do?

**Comment by tordanik** [comment]
I see two main ways of implementing it:
* [changing the criteria for autoconfirmed status](https://www.mediawiki.org/wiki/Manual:Autoconfirmed_users) to 0
* [changing group permissions](https://www.mediawiki.org/wiki/Manual:User_rights#Changing_group_permissions) to hand the rights to all users instead of just autoconfirmed users

According to MediaWiki help, both require editing `LocalSettings.php`. I haven't found a way to do something equivalent with admin/bureaucrat privlieges from within the wiki. I believe I cannot even manually grant autoconfirmed status, even though I _can_ assign users to other groups such as "admin".

**Comment by Tigerfell** [comment]
> I believe I cannot even manually grant autoconfirmed status, even though I can assign users to other groups such as "admin".

You can definitely not do this. It was changed for wiki.osm.org in openstreetmap/chef/pull/376, so admins can do it there. I actually do not know why there is a confirmation system for the private wikis anyway. I mean all those users are trusted, right? It is probably the default setting (which is reasonable if the wiki is publicly editable). I would suggest to limit user confirmation to publicly editable wikis (currently wiki.osm.org only). Does that sound like a reasonable solution? @Firefishy

**Comment by Tigerfell** [comment]
Some background information for tordanik: There is essentially one `LocalSettings.php` at [openstreetmap/chef/cookbooks/mediawiki/templates/default/LocalSettings.php.erb](https://github.com/openstreetmap/chef/blob/master/cookbooks/mediawiki/templates/default/LocalSettings.php.erb) for all OSM wikis (i.e. Board, DWG, MWG, OSMF, wiki.osm.org). The extensions used in all wikis are configured in separate files in the same directory. One would probably want to change the [configuration of RECAPTCHA](https://github.com/openstreetmap/chef/blob/master/cookbooks/mediawiki/templates/default/mw-ext-ConfirmEdit.inc.php.erb), too, otherwise new board members would still need to fill them out. 

@tomhughes I can write a PR if OWG approves the suggestions.
