### ISSUE TITLE
Support ip blocking on backend render servers

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#549]
We have a noticeable percentage of traffic on the backend servers coming from single IPs. So far these are always scrapers, because normal users have a high cache hit ratio, while scrapers have close to 0% cache hits.

This means that it would be safe to block based on `HTTP_FASTLY_CLIENT_IP` on requests. This would enable us to
- handle cases like QGIS where a minority of users are scraping with it, but we don't want to block all users
- automatically handle single IP scrapers
- relieve a lot of manual work

Users behind a NAT are not likely to be a problem - I do not currently see them as a significant source of single-ip traffic.
Proxies might be a problem. If there is a system for excluding IPs from the block list, it would need to be self-service with pull requests.

Thresholds for blocking that make sense are likely to be in the 50 000 per hour or higher range.

**Comment by tomhughes** [comment]
Are you just looking to block individual IPs or does it need to be able to handle netblocks as well? Would sending a 403 response be good or do we need to use a special code so that we can differentiate it at the fastly layer?

Also I wonder if having it in the public repo where pull requests could be accepted will be possible or if GDPR means we would have to keep the blocked addresses in the private repo where that wouldn't be possible...

**Comment by pnorman** [comment]
> Are you just looking to block individual IPs or does it need to be able to handle netblocks as well?

Individual IPs.

> Would sending a 403 response be good or do we need to use a special code so that we can differentiate it at the fastly layer?

I'd prefer a 429, but could work with 403. It's easier for us if it has its own error code since then we can figure out what's going on when someone complains.

> Also I wonder if having it in the public repo where pull requests could be accepted will be possible or if GDPR means we would have to keep the blocked addresses in the private repo where that wouldn't be possible...

These would be unblocked addresses, not blocked ones. GDPR is likely to add complications that might make it difficult or impossible. I'll try to get a picture of how much the proxies use and if they really help.

-----

Something else that occurs to me is that we need to set the limits as a property of the server. For example, if we say 100 000 per hour is the limit on pyrene, the only US server, it should be 50 000 per hour each on balerion and bowser, the two Australian servers.

**Comment by tomhughes** [comment]
So the PR would add to a whitelist that override the blacklist rather than just removing from the blacklist? What's the point of that? It makes things much more complicated...

Or are you imagining the blacklist coming from some source outside the chef repo? If so then where would that come from? Or are you saying you want the render servers to do dynamic rate limiting?

**Comment by pnorman** [comment]
I want something like Nominatim, except based on `HTTP_FASTLY_CLIENT_IP`.

**Comment by tomhughes** [comment]
Right. I misunderstood and thought you were just talking about a static blacklist curated by humans.

I don't think what you're asking for is really an operational matter - it's not something we can just do with existing tools but will instead require changes to mod_tile to implement it so that is probably a better place for this ticket.

**Comment by lonvia** [comment]
Nominatim did this 100% in Apache using rewrite lists. See https://github.com/openstreetmap/chef/blob/22c14f07fa7055967273e132d4438a4734c01519/cookbooks/nominatim/templates/default/apache.erb#L58 for the apache rewrite part and https://git.openstreetmap.org/nominatim.git/blob/HEAD:/utils/cron_ipanalyse.py for the script that analyses logs and writes the rewrite list.

**Comment by tomhughes** [comment]
Hmm how often does the cron job run? That seems like it would either be very slow to react or horribly inefficient...

I thought nominatim worked by having PHP do the initial rate limiting and then fail2ban monitor the logs to apply blocks to people that ignore the limiting.

**Comment by lonvia** [comment]
It did run every minute which was good enough for the access patterns for Nominatim. The server can take the load on heavy users for a while. If you just want to ban the worst tile offenders for a bit, it's probably good enough to update the block lists every 5 minutes or so.

**Comment by tomhughes** [comment]
Implemented in https://github.com/openstreetmap/chef/commit/28360d6f39fa7fe8229ed64b4c93d1d0405add47.
