### ISSUE TITLE
Travis CI management for the openstreetmap organization

### ISSUE THREAD

**Issue by Krakonos** [openstreetmap/operations#558]
Hi!

I just migrated the CI from travis-ci.org to travis-ci.com for openstreetmap/merkaartor. However, the builds are not working. The error message  "Could not authorize build request for openstreetmap/repo" appears to be the same for merkaartor, but also the stateofthemap-2021 repo and possibly others. According to the internet [1], it appears the org either does not have a plan activated, or has run out of build minutes. Is anybody managing the travis account?

I can try to get that solved. It appears travis allows me to activate the free plan for the osm org, and we could then ask for OSS build minutes for all our projects. However, I don't want to cause confusion in case somebody else is taking care of it - but in that case, I'd like to get an update on the state and ask if I can help in some way.

CI builds are vital for Merkaartor, as it's the preferred way to release windows and OSX builds and that is currently much needed in the release process that froze at rc1 due to the migration.

[1] https://stackoverflow.com/questions/41034694/travis-could-not-authorize-build-request/41078031

**Comment by tomhughes** [comment]
I did get the request to enable it but unfortunately github provides no context to such requests such as who is requesting them.

The trouble with enabling it is that the .com version of travis only provides very limited credits and there's no way to share them our among the multiple projects using this organisation so one project could use up all the credit and then nobody else would get a look in until the next month.

The open source program is pretty much useless as you have to keep going back and begging for more minutes - there's no way to get a regular increased allowance as I understand it.

All of which is why most projects have migrated to other solutions from than moving from .org to .com at travis.

**Comment by Krakonos** [comment]
Well, my project would be among the hungry ones (I need roughly 1350 credits for a build due to the expensive osx and windows builds). I'm not sure what the current state is, but the UI clearly says there is OSS credit replenished every month:
![image](https://user-images.githubusercontent.com/138209/128350688-3566c0e9-853c-479e-9bfc-afab806bf409.png)

We could try to nag them for a generous amount of monthly credits and see if it works out.

On the other hand, I'm open to migrating to something else, though I'd hate to migrate the build system _again_, not mentioning that I'm not aware of any other solution that does osx and windows builds that doesn't have the same limitations (like github actions). Ideas? Where did other projects move to?

**Comment by tomhughes** [comment]
My reading before was certainly that OSS credits were added on a one off basis but looking now I can see it does also say you can ask for a recurring allowance which at least makes more sense though it doesn't seem to be the default which is really quite odd - what sort of project only wants one off credits?!? The specific details are at https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source with the invitation to "discuss" recurring credits at the end.

I mean I can enable it at github but the initial credit allocation is only going to last you about 7 builds even if nobody else does anything and my concern is that travis are going to be a pain in the arse after that especially if they'll only talk to me (or one of the other organisation admins) so that we wind up having to constantly negotiate with them for more credits.

I'm not sure what you mean about github actions though - are you saying it can't do what you want?

**Comment by Krakonos** [comment]
Well, I think they originally promised to keep OSS free to use, then limited that to non-recurring allowances (that you could ask multiple times) and after some backlash reverted to this model. At least that's what I deduced from various (conflicting) materials on the web and the community forum.

Github actions would probably do what I need, but it's more or less the same story - 2000 minutes/month for the organization, but windows/osx minutes cost 8x the usual price. In my case, I need around 35 minutes on osx and windows (with travis, depends mostly on the builds speed when using homebrew and msys2's pacman), so 35*8 is around 280 minutes for one build.

Not sure if we can get any better conditions negotiated for github actions?

**Comment by tomhughes** [comment]
There's no limit on github actions for public repositories - the limit is only for private repositories. See https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions for details.

**Comment by Krakonos** [comment]
Thanks for pointing that out, it appears I have misread the conditions and assumed you get the "Free" plan. This looks like the easiest solution, so I'll see if I can migrate the scripts there. Closing the issue, would reopen if something serious happens.

**Comment by grischard** [comment]
@Krakonos you can have a look at what I've done on the josm repository to get github actions to build and package every commit.

**Comment by Krakonos** [comment]
@grischard Thanks, I already managed on my own. Just need a bit more testing due to the windows environment having different libraries preinstalled, but I have a working PR that runs more or less the same scripts as travis did. 

Actually, settings up github actions was easier than travis, mostly due to more or less native msys2 support using the setup-msys2 action.
