### ISSUE TITLE
Backfill missing tile log files

### ISSUE THREAD

**Issue by brawer** [openstreetmap/operations#580]
Huge thanks for fixing https://github.com/openstreetmap/operations/issues/574! Do you plan to backfill the missing files? (Just hoping, perhaps you could also backfill the tile log files from December 2020 and April 2021, where log files exist but are mostly empty because of https://github.com/openstreetmap/operations/issues/485?)

**Comment by tomhughes** [comment]
I'm not sure it's worth backfilling every day unless you have a compelling reason? We could probably do one a month or something though.

**Comment by tomhughes** [comment]
Also @pnorman might be able to comment on whether reprocessing old logs is going to have costs beyond what we would have paid anyway, for example if the older logs have been moved to a lower storage tier meaning that analysing them will be more expensive?

**Comment by pnorman** [comment]
> Also @pnorman might be able to comment on whether reprocessing old logs is going to have costs beyond what we would have paid anyway, for example if the older logs have been moved to a lower storage tier meaning that analysing them will be more expensive?

We're okay here - they're in standard storage. 

I'd prefer to backfill to allow year over year comparisons and allow time-based displays of tile views to not have a big hole.

**Comment by brawer** [comment]
Thank you! The background of my request is the [Wikidata QRank project](https://qrank.toolforge.org/), where we’d like to compute a ranking signal on geographic Wikidata entities by aggregating OSM tile logs over several years. We don’t actually need all past logs; whatever is around will do. Still, if it’s not too much work and not super expensive, it would be really nice if you could backfill the past missing data. Especially the first half of 2021, where files are currently present but have bogus content. Having the logs data in a consistent state (without a need to special-case for the past time periods when the logs pipeline was broken) will make life easier, surely also for your other data consumers.

**Comment by tomhughes** [comment]
The missing logs have been backfilling since this morning - it's working it's way backwards and is currently in October.

By "bogus content" you mean the very short files before 13th April I assume? We can regenerate those if we have the necessary underlying data - @pnorman probably knows better than me how far back we can go on the new infrastructure.

There will be a period of a few months at the end of 2020 when traffic was split over the old and new infrastructure and it would be hard to produce data for there even if we have the logs.

**Comment by pnorman** [comment]
> aggregating OSM tile logs over several years

You shouldn't do this. Between the start and 2021-04-12 the logs analyzed were those of the second level of caching in our CDN, which means they were measuring something different than current logs which are measuring successful requests to the CDN.

I chose the 2021-04-13 as a start date for logs on the new system because there was a configuration bug which allowed some poison-pill content into the logs of 2021-04-12.

**Comment by tomhughes** [comment]
Backfilling has completed now - there is still one day, 2021-07-23, missing due to #581.
