### ISSUE TITLE
Error: The post table and topic table seem to be out of sync!. at forum.openstreetmap.org

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#584]
https://forum.openstreetmap.org/viewtopic.php?id=11155&p=27

**Comment by tomhughes** [comment]
Sure. Not sure what you expect me to do about it though?

**Comment by tomhughes** [comment]
I have a vague memory this is just a bug in phpbb that when the number of posts is an exact multiple of the page size it shows a link for the next page but then blows up when you try and access it because there are no posts - will be interesting to see if it stops when somebody posts another message to the topic.

**Comment by tomhughes** [comment]
Certainly there are exactly 650 posts in that topic, so there is nothing to show on page 27 currently.

**Comment by matkoniecz** [comment]
Thanks, dummy post worked.
