### ISSUE TITLE
Maybe recommend using tile caching proxy in Tile Usage Policy?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#586]
Or is it not mentioned as obvious? Or because it would imply that serious large-scale use is viable?

https://operations.osmfoundation.org/policies/tiles/

**Comment by tomhughes** [comment]
I think @pnorman said it's better if people don't, or at least it doesn't matter much now we're using fastly.

**Comment by pnorman** [comment]
A caching proxy like nginx is not recommended. Generally if it would be in the cache, it would be in Fastly.

Something like mapproxy may be of value in limited cases because it can use map tile specific logic and store tiles for much longer, but it really requires an expert understanding of caching to know if it would be any good.

Caches also tend to have problems with being configured incorrectly for user-agent and host headers.
