### ISSUE TITLE
Falling back to SSLv3 because host is TLS intolerant:openstreetmap.org

### ISSUE THREAD

**Issue by assoft89** [openstreetmap/operations#587]
Forwarded to open to openstreetmap.org on older versions of Android. Error:
Falling back to SSLv3 because host is TLS intolerant: openstreetmap.org:443
Can you tell me if you can pass the required parameter in the GET header so that the host will allow connection from devices that do not support the new TLS / SSL protocols?

**Comment by tomhughes** [comment]
I don't understand what you mean.

Neither GET parameters or HTTP headers have any effect on SSL/TLS negotiation because that happens before the request is sent.

We require TLSv1.2 or later and we haven't supported SSLv3 for a very long time.

All versions of Android from 4.4.2 onwards should work - older versions are unlikely to work when using the standard SSL stack though some applications may work by using alternate stacks.
