### ISSUE TITLE
Create an automated timeline for hardware changes

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#59]
We now have https://hardware.openstreetmap.org/ which is awesome. But it only shows the live information, so it's hard to figure out e.g. when extra RAM was added, or BIOS updated, etc.

It would be good to have this information available somewhere, for owg-log, budgeting and troubleshooting reasons. Matt has done some work I believe on trying to detect changes between the chef JSON files, but ran into problems with e.g. non-stable arrays of information produced by ohai. @zerebubuth any comments?

Does anyone have any rough ideas what such a system would look like, or anything in particular that would be useful to record?

**Comment by pnorman** [comment]
We've been specifying hardware that will last longer without upgrades, so this type of information is less important than it used to be.

Although I'd like some kind of automated system, given how long this issue has been open without discussion, I'm going to close it to keep the priority on more urgent work.

Personally my concern is not upgrades, but how services move between machines (e.g. the wiki was on ouroboros then moved to tabaluga with last years upgrades). My comments about monitoring/metrics that are [service focused instead of system focused](https://github.com/openstreetmap/operations/issues/360#issuecomment-590026197) are related.

**Comment by harry-wood** [comment]
Coincidentally I was just looking around to see if I can see when the wiki was moved from ouroboros to tabaluga :-)

**Comment by Firefishy** [comment]
I'm reliant on https://web.archive.org/web/ for looking up old data. I'd really like this feature to be integrated into hardware.osm.org

**Comment by tomhughes** [comment]
However "nice" it would be keeping a history would require a completely different architecture - basically you'd have to pretty much start from scratch.
