### ISSUE TITLE
Taginfo instance seems to have dropped most relations

### ISSUE THREAD

**Issue by imagico** [openstreetmap/operations#598]
See:

https://taginfo.openstreetmap.org/tags

compared to:

https://taginfo.geofabrik.de/europe/tags

**Comment by joto** [comment]
The update running on March 6 had a problem: Probably a temporary network error when downloading the diffs triggered a re-run of the planet update. But when that ran, the tmp planet from the earlier run was also around and the disk [was full midway though that run](https://munin.openstreetmap.org/openstreetmap.org/grindtooth.openstreetmap.org/df.html). This wasn't handled properly. This is also why the log file from the event is incomplete.

Todos:
* [ ] Update pyosmium-up-to-date, because since version 3.1.3 it is more resilient in those cases. @tomhughes , can you do that?
* [ ] Improve scripts, so they don't create more copies of the planet: See https://github.com/openstreetmap/chef/pull/486
* [ ] Set up from old planet again (I'll do that once everything else is done)

**Comment by pnorman** [comment]
Does 3.1.3 fix the error handling for out of room? Or was an error missed and not propagated up?

**Comment by joto** [comment]
> Does 3.1.3 fix the error handling for out of room? Or was an error missed and not propagated up?

The latter. pyosmium-up-to-date differentiates between return codes
* 0 - everything okay
* 1 - work partially done (i.e. some diffs were applied but not all)
* everything else - hard error

In this case it seems 1 was returned instead of something > 1. This was a bug that was fixed in 3.1.3.

I am not 100% sure updating pyosmium-up-to-date will fix everything. Because of the full disk the log file was not complete so we couldn't see exactly what happened, but it is definitely a step in the right direction. :-)

**Comment by joto** [comment]
Taginfo run tonight went well. From my point of view we can close here once pyosmium-up-to-date was updated.
