### ISSUE TITLE
Failed disks in ramoth

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#60]
```
The following warning/error was logged by the smartd daemon:

Device: /dev/sg2 [megaraid_disk_16], SMART Failure: HARDWARE IMPENDING FAILURE GENERAL HARD DRIVE FAILURE

Device info:
[SEAGATE  ST3600057SS      ES68], lu id: 0x5000c50042fc715f, S/N: 6SL274X8, 600 GB
```

**Comment by Firefishy** [comment]
6SL273Z4 and 6SL274X8 showing "SMART Failure: HARDWARE IMPENDING FAILURE GENERAL HARD DRIVE FAILURE"

6SL273Z4 has been ejected from the array. LSI tools show the disk as ES686SL273Z4 (Firmware + Serial).

I have asked @woodpeck to order 2 replacement disks.

**Comment by zerebubuth** [comment]
Disks arrived, @Firefishy handed them off, and the one failed disk was replaced. That's now in copyback, currently done 19% and ETA to finish is tomorrow around noon.

It was felt that it was too risky to yank the other disk while the copyback was in progress, so that'll have to happen at a later visit in the next few days.

**Comment by zerebubuth** [comment]
Final disk replaced, displacing the existing hot spare. I've assigned the new drive as the new hot spare. So once the old hot spare has been rebuilt, everything should be OK. ETA on that ~24h (currently 8% done).
