### ISSUE TITLE
garmin.openstreetmap.nl: try help to fix it

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/operations#615]
I've been asked if there is anything that I can do to help fix http://garmin.openstreetmap.nl/

It has been non-functional for a long time and reflects badly on OpenStreetMap. The site is the first site most people find when attempting to find OpenStreetMap maps for Garmin. 

OWG/DWG/Others has received many misdirected complains about the site in the past.

**Comment by Firefishy** [comment]
Most of the site seems to run via: osm.pleiades.uni-wuppertal.de

**Comment by Firefishy** [comment]
The site used to be maintained by Lambertus, but he appears to be unreachable.

**Comment by Firefishy** [comment]
There has been previous attempts to move the site forward: https://forum.openstreetmap.org/viewtopic.php?id=66190

**Comment by Firefishy** [comment]
I have reached out to uni-wuppertal.de, they have confirmed that osm.pleiades.uni-wuppertal.de was/is operated by Lambertus. They have agreed to turn off the service in Lambertus's absence.

Dear Reader: There has been a many years of requests trying to reach Lambertus, but he has walked away from the project and is unresponsive. His private email domain expired at the beginning of 2022. We had a similar problem with forum.openstreetmap.org which was also once hosted by Lambertus, it was a painful process to recover it and move it back to OSM operations team hosting.

**Comment by Firefishy** [comment]
I have reached out to Stefan de Konink asking if he could shutdown or redirect the site, at the moment he appears to be unwilling to do this. He suggested containing the openstreetmap.nl admins, but was unwilling to provide any names.

**Comment by Firefishy** [comment]
Have gone ahead and blocked the garmin.openstreetmap.nl referrer from requesting tiles from tile.openstreetmap.org
Happy to unblock if the site works again and has someone to support it, until then this is one of the only ways we're able discourage people from using the broken service. Until now, the site has accepted Garmin map requests, but never processed them, causing intense frustration for users.

**Comment by Firefishy** [comment]
I have reached out to @mvexel to see if he can help.

**Comment by Firefishy** [comment]
I have reached out to Henk Hoff to see if he can help.

**Comment by mmd-osm** [comment]
A few more ideas: 
* https://forum.openstreetmap.org/viewtopic.php?id=2625 -> change thread title to say that the service is dead, remove URL in thread title
* https://forum.openstreetmap.org/viewtopic.php?pid=16939#p16939 -> remove defunct contact details, add big fat warning that the service is gone

**Comment by skinkie** [comment]
Willing to help to actually come up with a sustainable alternative, but not in the way the cards are played in private.

**Comment by Firefishy** [comment]
> A few more ideas:
> 
> * https://forum.openstreetmap.org/viewtopic.php?id=2625 -> change thread title to say that the service is dead, remove URL in thread title
> * https://forum.openstreetmap.org/viewtopic.php?pid=16939#p16939 -> remove defunct contact details, add big fat warning that the service is gone

Updated the post. Happy to modify the text if what I have posted is not suitable.

**Comment by skinkie** [comment]
> I have reached out to @skinkie asking if he could shutdown or redirect the site, at the moment he appears to be unwilling to do this. He suggested contacting the openstreetmap.nl admins, but did not provide any contact names, despite asking.

@StichtingOpenGeo handles the financial espects of the domainname, of which I am a board member of, and have access to the technical steps for DNS management. I disagree on the steps @Firefishy did with respect to directly addressing sponsors, and reached out to OSMF on this topic.

**Comment by woodpeck** [comment]
I think that anyone who *could* have done something about the situation in the last two years - even if that had just been replacing the site with a "sorry this doesn't work" instead of happily accepting requests and leaving tens of thousands of users to wonder why they get no response - but then chose to ignore it is not in a position to complain. The amount of unnecessary friction this non-working page has created on all sides is hard to measure. I'm sure the sponsors have had their share of end-user inquiries. This was already painful in 2019 when it was last discussed, and has only worsened since. Taking the axe to it is a sensible course of action, and frankly I wouldn't waste any more time talking to people who knew of this issue for years without taking action. If they didn't do anything for years why should they be of any help now.

**Comment by Firefishy** [comment]
@eelkevdbos ^^

**Comment by Firefishy** [comment]
@skinkie posted to talk-nl: https://lists.openstreetmap.org/pipermail/talk-nl/2022-May/015667.html
My reply: https://lists.openstreetmap.org/pipermail/talk-nl/2022-May/015668.html

**Comment by Firefishy** [comment]
> @woodpeck the question I have asked before was quite simple: which service is a true alternative for it? The only reply that came up was: point it to the wiki. I have obviously asked the people asking for support (I receive all the webmaster e-mails) why they still took that site, instead what was on the wiki. The reply is virtually the same: custom maps.

Any service with provides users with a working experience is better than what is available on garmin.openstreetmap.nl (infinite waiting in vain for a garmin map that will never come). Within 2 clicks on the wiki I am able to download a garmin map that works: https://wiki.openstreetmap.org/wiki/OSM_Map_On_Garmin/Download

**Comment by Firefishy** [comment]
https://www.openfietsmap.nl/ is another good replacement.

**Comment by skinkie** [comment]
> You are operating a site that promises free ponies to everyone but doesn't deliver.

STOP. I am not operating any site under that domain, I only handle the technical and content questions for OpenStreetMap in The Netherlands.

**Comment by skinkie** [comment]
> https://www.openfietsmap.nl/ is another good replacement.

Already contacted @ligfietser Lets see if he replies faster than _Lambertus_.

**Comment by gravitystorm** [comment]
> I wouldn't waste any more time talking to people who knew of this issue for years without taking action. If they didn't do anything for years why should they be of any help now.

Who says they need to help? If the owners of the openstreetmap.nl domain are happy with the current situation, then that's their ballgame. If I ran something relating to openstreetmap under a subdomain somewhere, and I was ignoring the project and anyone complaining about it, I'd be pretty miffed to then find OSMF contacting my hosting provider asking for it to be shut down. (For example, I operate several abandoned OSM projects on dev.osm.org, so perhaps one day they will come for me - albeit the hosting provider there is OSMF already so it's not exactly the perfect analogy! :smiley: ).

OSMF doesn't own the openstreetmap.nl domain, which was registered in good faith in 2007 and long before OSMF had any trademark policy. OSMF needs to accept that, even if they might wish it was different. I get how the situation is frustrating, but so be it.

If OSMF are really that bothered about this situation, then I can suggest some other more cooperative approaches, not limited to:
* It seems unclear who actually owns the openstreetmap.nl domain. From what I see it's either [Stichting Vrijschrift.org](https://forum.openstreetmap.org/viewtopic.php?pid=749087#p749087) or [Stichting OSGeo](https://github.com/openstreetmap/operations/issues/615#issuecomment-1116047930). OSMF could seek to clarify who the owner of the domain is, which might not be who pays for it, and try to persuade them to make the changes to fix it or redirect it or whatever.
* If the owner of openstreetmap.nl isn't interested in changing anything, then OSMF needs to accept that. It's not their domain, it's not their situation to control.
* If so, then the OSMF can focus on working around the broken site. The OSMF can set up their own site, or promote an existing alternative, in order to out-rank the broken site in search results. They can contact other sites that link to the broken site, and update their link. And all that kind of stuff. Time consuming, but again if you can't control the source of the problem, you have to focus on workarounds.
* The OSMF can explain the situation, and potential ways forward, to the OSM Netherlands community, and they can decide the best way forward. That might include members of the relevant organisation(s) taking the lead on fixing the situation from within, or changing which organisation is responsible for the domain, or whatever they see fit to do.

I suspect the underlying answer will be that it's unclear, even to people with positions in the organisation(s) involved, exactly who owns what and who gets to make any tough decisions regarding the domain. I know that many volunteer organisations are very poor at writing down exactly who has the authority to do what, so I wouldn't be surprised to find that there's zero internal documentation and everyone thinks someone else should be making the hard decisions something, and so some empathy with the volunteers in those organisations might be required.

But the main theme is that this is an organisational, not a technical, problem, and attempting to bypass the organisational problem to institute a technical fix is the wrong strategy.

**Comment by Firefishy** [comment]
> I'd be pretty miffed to then find OSMF contacting my hosting provider asking for it to be shut down.

I did not ask uni-wuppertal.de to shut down garmin.openstreetmap.nl or the backend at osm.pleiades.uni-wuppertal.de. I asked them to put me into contact with the backend site admin, they replied Lambertus manages the sites.

garmin.openstreetmap.nl is hosted by Oxilion who I have not contacted. Per this thread I have reached the admins of OpenStreetMap.nl, one of which had decided to make a complaint with my new employer on my 1st day ;-)

**Comment by skinkie** [comment]
> * It seems unclear who actually owns the openstreetmap.nl domain. From what I see it's either [Stichting Vrijschrift.org](https://forum.openstreetmap.org/viewtopic.php?pid=749087#p749087) or [Stichting OSGeo](https://github.com/openstreetmap/operations/issues/615#issuecomment-1116047930). OSMF could seek to clarify who the owner of the domain is, which might not be who pays for it, and try to persuade them to make the changes to fix it or redirect it or whatever.

It transfered from Vrijschrift to OpenGeo (different than OSGeo). OpenGeo was already managing it for years, but now also pays for it.

> But the main theme is that this is an organisational, not a technical, problem, and attempting to bypass the organisational problem to institute a technical fix is the wrong strategy.

Exactly.

**Comment by skinkie** [comment]
> When the policy was enacted everybody was given the possibility to obtain a licence and legalize their prior unlicensed use, so trying to paint the OSMF as heavy handed in protecting its IP is particularly disingenuous.

@simonpoole is your argument that the openstreetmap.nl **domain** falls under the trademark of OSMF? I would love to receive your feedback on that one. Because it is basically again some kind of statement that OSMF is tolerating the Dutch communty which is infridiging their _rights_.

![image](https://user-images.githubusercontent.com/502394/166486755-246c8e18-7064-4118-b325-5cd9f1242415.png)
(Received 2008-11-03)

![image](https://user-images.githubusercontent.com/502394/166486926-303ef01a-7bef-40d5-92a9-609e6b5c5eef.png)
(Registred 2007-03-06)

Because while it has absolutely nothing to do with the issue at hand. The repeating threats over the copyright in all possible forms, really really start to annoy me.

**Comment by Firefishy** [comment]
> All that said if @skinkie wants to keep the garmin site "alive" he's obviously free to do so, but the use of OSMFs IP needs to be limited to nominative use.

"Free worldwide Garmin maps from OpenStreetMap" title of the site should be fixed. It is not OpenStreetMap providing the Garmin maps.

**Comment by gravitystorm** [comment]
> I have reached out to uni-wuppertal.de, they have confirmed that osm.pleiades.uni-wuppertal.de was/is operated by Lambertus. They **have agreed to** turn off the service in Lambertus's absence.

> I did not ask uni-wuppertal.de to shut down garmin.openstreetmap.nl or the backend at osm.pleiades.uni-wuppertal.de. I asked them to put me into contact with the backend site admin, they replied Lambertus manages the sites.

These statements seem to conflict, or have some subtlety that's not clear to me, particularly the bit I've highlighted. But it's not super important, since I think it's really up to OpenGeo who runs what and what should be shut down or not.

> ... all use was **unlicensed** without explicit permission ... to stop **infringing** use ... **legalize their prior unlicensed use** ...

Ha! I think OSMF needs zero help from me to portray themselves as heavy-handed, with that kind of language. My advice would be to simply not mention trademarks, or even hint at any legal action, again in any of this conversation, and OSMF might then be a bit more likely to achieve their goals without getting everyone's backs up. Going down the "we have a trademark, technically you are infringing it, blah blah blah" is, how shall I say it, a tad inflammatory.

**Comment by gravitystorm** [comment]
> It transfered from Vrijschrift to OpenGeo (different than OSGeo). OpenGeo was already managing it for years, but now also pays for it.

Sorry for the typo, I've fixed it in my comment. 

And thanks for the clarification. I hope the OSMF reps here step back from waging the legalise battles, take a deep breath, and start again with offering to help.

**Comment by Firefishy** [comment]
> > I have reached out to uni-wuppertal.de, they have confirmed that osm.pleiades.uni-wuppertal.de was/is operated by Lambertus. They **have agreed to** turn off the service in Lambertus's absence.
> 
> > I did not ask uni-wuppertal.de to shut down garmin.openstreetmap.nl or the backend at osm.pleiades.uni-wuppertal.de. I asked them to put me into contact with the backend site admin, they replied Lambertus manages the sites.
> 
> These statements seem to conflict, or have some subtlety that's not clear to me, particularly the bit I've highlighted. But it's not super important, since I think it's really up to OpenGeo who runs what and what should be shut down or not.
> 

I have updated that entry as it wasn't clear. It was uni-wuppertal.de Admins who offered to remove the DNS for osm.pleiades.uni-wuppertal.de without my promoting, I they have likely received complains about the service in the past. I did not ask for the service to be shutdown. I suspect osm.pleiades.uni-wuppertal.de was only run by Lambertus and not managed by anybody from OpenStreetMap.nl.

**Comment by skinkie** [comment]
> I have yet to see anybody weigh in on any of these matters from the Dutch community than you, just as OpenGeo seems to be mainly you. So I'm assuming you are simply representing yourself without any mandate from anybody else.

Thank god we as organisation are an _actual_ non-profit with the mandatory publication requirements, and you are just an individual making inaccurate statements.

> But in any case the legal situation is clear, the OSMF holds a valid trademark in the Netherlands with all the associated rights and please stop the hyperbole, the statement of a fact isn't a threat.

Does it hold an trademark on a _trade name_ operating before the trademark? Dieing to know if OSMF wants to find out that one.

**Comment by Firefishy** [comment]
Please can we keep this thread to garmin.openstreetmap.nl. Discussions on trademark can be had elsewhere.

**Comment by SomeoneElseOSM** [comment]
@skinkie As one of the people who've been fielding "OpenStreetMap is broken" questions at https://forum.openstreetmap.org/viewforum.php?id=26 and elsewhere for ages, I stand by everything I said almost exactly two years ago at https://forum.openstreetmap.org/viewtopic.php?pid=748424#p748424 .   I find it incredible that you complained about "threats" then at https://forum.openstreetmap.org/viewtopic.php?id=66190 , did apparently nothing to help resolve the issue, and are complaining again now.

Regarding "this is an organisational, not a technical, problem" above - organisational approaches have been tried repeatedly for years now - lots of people have tried to help and failed (just look at the threads on the forum).

**Comment by Firefishy** [comment]
> Have gone ahead and blocked the garmin.openstreetmap.nl referrer from requesting tiles from tile.openstreetmap.org Happy to unblock if the site works again and has someone to support it, until then this is one of the only ways we're able discourage people from using the broken service. Until now, the site has accepted Garmin map requests, but never processed them, causing intense frustration for users.

I have now removed the referer block for garmin.openstreetmap.nl. We currently do not have a [tile usage policy](https://operations.osmfoundation.org/policies/tiles/) that would justify the site being blocked. I will raise via a separate process suggested policies to justify these sorts of blocks in any potential future cases.

**Comment by skinkie** [comment]
We are also in the process of sorting things out technically. I wouldn't say hold your breath, you would probably literally run out the TTL.

**Comment by Firefishy** [comment]
garmin.openstreetmap.nl now carries a notice and then redirect to https://extract.bbbike.org/

Sorry being a bull in a china shop, I should have been more tactful in the handling of this. @skinkie I appreciate your work to resolve the issue, sorry for being tactless in my handling.
