### ISSUE TITLE
Tiles not loading, throwing 404

### ISSUE THREAD

**Issue by adammpkins** [openstreetmap/operations#633]
Several tiles randomly are not loading on my map which is instantiated using leaflet.

3968.png:1 
 GET https://b.tile.openstreetmap.org/13/4094/3968.png 404
3967.png:1 
 GET https://c.tile.openstreetmap.org/13/4090/3967.png 404

As you can see when hitting these links, they are currently throwing 404.

**Comment by Firefishy** [comment]
Tiles are rendered on-demand (and cached), during periods of high load it is possible a tile may not be rendered quickly enough and a 404 is served, this behaviour is by design to avoid overloading the server.

PS: Best to use https://tile.openstreetmap.org/ (instead of (a|b|c).tile.openstreetmap.org format.
