### ISSUE TITLE
pyrene serving old tiles before it should

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#658]
Pyrene is configured to start dropping rendering requests at a load average of 1000

https://github.com/openstreetmap/chef/blob/12007a1850cedfabce76c6802ccc9ffca3e6f027/cookbooks/tile/templates/default/tile.conf.erb#L16-L17

This is not what's happening. Instead, when it hits 50 load, it starts load shedding, keeping the load average at 50.

![image](https://user-images.githubusercontent.com/1190866/175135197-4e57cc9b-d9f3-40e7-a76c-24e7d9c59aa5.png)

50 is suspicious, because the default ModTileMaxLoadMissing is https://github.com/openstreetmap/mod_tile/blob/42e4f0d283ba31c9e36077d64e57c9ab66f95ae9/includes/render_config.h#L39

Before I start investigating a mod_tile bug, do we think there's any possibility the config isn't getting loaded into apache?

This isn't a serious issue for pyrene because at about 50 load, CPU is >90% usage, but for the new servers with their 112 hardware threads, it could be a problem if we got them to full load.

**Comment by tomhughes** [comment]
I'm not sure your diagnosis is correct. Looking at the sort if it was triggering the load limit then it should log at level info with:

```
Load (%f) larger max_load_missing (%d). Return HTTP_NOT_FOUND.
```

but I just turned the log level up and forced the load up to 60 and got nothing like that in the log.

Is the issue not just that the load will never go much above 50 because we limit the render threads to 39 which combined with apache itself and postgres is going to limit the theoretical maximum load to much less than 1000.

It will still fail over to a 404 after 10 seconds if the tile hasn't been rendered of course.

**Comment by tomhughes** [comment]
Given that odin has about 40% more render threads than pyrene it peaking at about 40% higher load average certainly sounds about right.
