### ISSUE TITLE
spamhaus reject open resolver query -> incoming mail for mailing list got bounced

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/operations#674]
spamhaus now return an error code when the dns query flow via open resolver is too high
the mta @ osm.org then bounce incoming mail.
`Destinataire : tagging@openstreetmap.org
Erreur : 550 Error: open resolver; https://www.spamhaus.org/returnc/pub/2400:cb00:377:1024::ac46:58b3`

**Comment by tomhughes** [comment]
Can you explain what on earth that means and what it has to do with us? What is an open resolver?

**Comment by tomhughes** [comment]
Also spamhaus don't reject anything - they classify things and it is up to the user of spamhaus services to decide what to do with any information they provide.

**Comment by tomhughes** [comment]
Spamhaus don't appear to have any issue with that address: https://check.spamhaus.org/not_listed/?searchterm=2400:cb00:377:1024::ac46:58b3

**Comment by tomhughes** [comment]
The phrase "open resolver" does not appear anywhere in our reject log for today.

Also that message is not the correct format - if we had rejected because the spamhaus zen list (which we do check) included the address then the message would be:

```
Rejected because <address> is in a black list at zen.spamhaus.org
<spamhaus description>
```

So wherever that bounce came from I don't think it was us.
