### ISSUE TITLE
Varnish based tile caches

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/operations#7]
Need to finish off the varnish based tile caching system...

**Comment by Firefishy** [comment]
Started sketching setup out using vagrant: https://github.com/Firefishy/osm-varnish-tile-cache

**Comment by miyurusankalpa** [comment]
@tomhughes any updates regarding this?

1.  I couldn't find any varnish related cookbooks on https://github.com/openstreetmap/chef/tree/master/cookbooks

2. Year ago you added squid 3 to https://github.com/openstreetmap/chef/commit/874b26a17120e4000178b246f292a7cbed8e2a46

3.  Servers I tested were still using squid 2.7  which is **CONSIDERED DANGEROUS** on https://wiki.squid-cache.org/Squid-2.7

3. Also as per https://github.com/openstreetmap/operations/issues/142#issuecomment-273108355 this issue also seems to be blocking IPv6 deployment on tile cache servers, which most of the servers supports.  https://hardware.openstreetmap.org/#tile-caches

I would love help if a clear road map is given. Thanks.

**Comment by tomhughes** [comment]
Squid 3 proved to be unworkably unstable to we had to abandon that effort.

Varnish still does not support the tar pit style rate limiting we do.

**Comment by Firefishy** [comment]
In addition, Varnish does not have a native implementation of cache-peering.

**Comment by tomhughes** [comment]
It also doesn't have a persistent cache and I'm not sure how well we would stand up if caches that were under full load restarted for any reason, especially if lots of them did it simultaneously.

I'm considering having another go at squid 3 but trying a larger block size, or maybe a tiered cache that is split into different blocks sizes but setup to stop cache entries being fragemented across blocks which is what both @woodpeck and I found seems to cause stability problems.

**Comment by grischard** [comment]
nginx apparently does tarpitting, and definitely persistent caching. But the last time I mentioned spending time on this, I was told it would be better invested in vector tiles?

**Comment by pnorman** [comment]
I don't think we need persistent caching. Wikimedia did a good analysis of their setup and considered the risk of CDN-wide tile purges. They found no problems that prevented them from switching from a persistent cache to a non-persistent one.

> But the last time I mentioned spending time on this, I was told it would be better invested in vector tiles?

The efforts are independent. Vector tiles will require a CDN too.

**Comment by tomhughes** [comment]
@grischard I do wonder how much the tar pitting really helps over just rejecting requests, which varnish could easily do...

@pnorman I read the wikimedia analysis but a lot of it is specific to their setup - part of it I think was they have multiple layers of caching and the risk of them all restarting at one was small but that doesn't apply to us.

**Comment by zorun** [comment]
Varnish does have persistent caching, although it is marked experimental: https://varnish-cache.org/docs/6.2/users-guide/storage-backends.html#persistent-experimental

From what I understand, Nginx caching is probably not expressive enough to implement OSM's complex tile serving policy?

**Comment by tomhughes** [comment]
Yes an "experimental" feature is exactly what we want to be using for our production cache network...

**Comment by zorun** [comment]
@tomhughes of course, I was not suggesting using it

**Comment by tomhughes** [comment]
We are actually quite close to being able to upgrade to squid 4 I think which would be something - we have been running it in production on one of our caches for about six weeks or so now.

If we could just get a fix for https://bugs.squid-cache.org/show_bug.cgi?id=4961 then we could probably think about rolling it out more widely...

**Comment by zorun** [comment]
@Firefishy @tomhughes how do you plan to proceed with testing Varnish? Do you have a synthetic load test, or can we just shift temporarily some production load to a varnish cache at a non-peak hour and look at the resulting statistics?

I am setting up a machine this is identical to noomoahk (same OS, RAM, CPU, disk, network) and plan to deploy @Firefishy Varnish configuration on it, so that we can compare apples with apples.

**Comment by tomhughes** [comment]
We're nowhere near even considering any question of testing anyway because we don't, as far as I know, have any plan how to configure it in a way that is usable.

Specifically, the point that you've identified, that there is no persistent caching, is something that I strongly suspect is a deal breaker, although not everybody agrees with me on that.

As far as testing goes we would just have to send some production load - we have no other way to test anything.

**Comment by zorun** [comment]
It's a tradeoff, I suspect that varnish is so fast *precisely* because it does not persist its cache (among other things).

On the whole, I agree that the worst case with no persistence looks bad (all caches reboot at the same time), although it sounds like it shouldn't happen very often, and there is a second layer of caching on the render servers anyway.

To make my point clear: I believe it's still interesting to test the preliminary performance of new caching software (Varnish or others), to know if it really makes a big difference with respect to CPU or I/O usage. If the answer is yes, it mean we can invest time to think about how to properly integrate that new software in the current stack.

**Comment by tomhughes** [comment]
The concern about what happens if a number of caches restart simultaneously (which absolutely will happen) is not about the performance of the caches, it's about the impact on the render servers of suddenly receiving ten times the normal number of requests.

**Comment by lyxys** [comment]
I think it would make sense to go to a two-tier cache setup then: having "distribution caches" with persistent storage associated with rendering nodes, which would basically look like our current tile caches, and "frontend caches" serving tiles to end users. These frontend caches would get their tiles from the distribution caches but would not need a persistence layer of their own.

**Comment by lyxys** [comment]
On second thought, the distribution caches would no longer need the rate limiting functionality, because they would only talk to the frontend caches. So the frontend caches would need rate limiting but no persistence layer, and the distribution caches would need persistence layer but no rate limiting.

**Comment by pnorman** [comment]
As we are moving to a commercial CDN this issue is now moot.
