### ISSUE TITLE
Nominatim errors from openstreetmap.org

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#742]
Right now when searching on osm.org, the nominatim results return 

> Error contacting nominatim.openstreetmap.org: Failed to open TCP connection to nominatim.openstreetmap.org:443 (execution expired)

A possible cause is a service disruption to IPv6 at OSUOSL, where one of the nominatim servers is hosted.

**Comment by tomhughes** [comment]
Yes obviously that is the cause - opening a ticket for the network issue (or contacting OSU about it!) would be more useful.

**Comment by tomhughes** [comment]
Pushed https://github.com/openstreetmap/dns/commit/01e60562bb11083b9865ffde958199b9ae2ab71b as a temporary fix.

**Comment by STPKITT** [comment]
This issue needs to be re-opened I think since I experience this issue since some days at least (can't remember since when exactly). I initially thought that my browser's settings were too strict so that something was blocked or so but right now I decided to try it in other browsers, both Firefox- and Chromium-based ones, the latter even naked with a clean profile.

**Comment by tomhughes** [comment]
We're not going to reopen a two year bug just because you're seeing the same symptoms - if it has come back then it will probably be a different issue and should be a new ticket.

That said I don't think you're even seeing the same symptoms because if you were then everybody else would be too because he issue here was nothing to do with the client browser but was to do with a connection between two of our servers in different data centres and if that had broken again it would be broken for everybody.

**Comment by STPKITT** [comment]
Well, I got the exact same error message, which is all I know. However, in the meantime the issue was fixed since it's currently working again.

**Comment by tomhughes** [comment]
If it was yesterday afternoon then that was probably down to some network issues with the network provider in one of our data centres but you made it sound like it had been happening for some time and we've received no other reports of that as far as I know.
