### ISSUE TITLE
Give more love to the prom dashboard :-)

### ISSUE THREAD

**Issue by grinapo** [openstreetmap/operations#814]
Some suggestion:
- check around the dashboards, some graphs are empty
- please enable shared crosshair, it would make seeing correlations much easier
- please enable "all" option in places where it's useful, for example summarizing apache metrics would be meaningful.
- set the default grafana dashboard to something, instead of "browse", or at least _star_ the default dashboards to make them easily selectable.

**Comment by tomhughes** [comment]
There are usually good reasons for the first - some graphs only work for certain machines for example but if you have specific examples then I can investigate.

Is the second something that can be done globally or something that has to be done on each dashboard? or each graph? I recall seeing references to it but I'm not sure where.

As far as I know the third is already done where it makes sense but again if you have examples where you feel it would be useful I can investigate.

How do I set the default dashboard? I thought I had done everything I could - there is a public list which is set as the default view I thought?

**Comment by grinapo** [comment]
> There are usually good reasons for the first - some graphs only work for certain machines for example but if you have specific examples then I can investigate.

It is not important for me, so I just trying to help with observations, but if it's good for you this way then it's good for me, too. :-)

- Squid offers no host
- Discourse is empty for all sites, which is just community 
- API database detail graphs empty for all

(At site Amsterdam it's weird that the two power supply have 12°C temp and 25% rel humidity difference, but that's not the dashboard's problem.)

> As far as I know the third is already done where it makes sense but again if you have examples where you feel it would be useful I can investigate.

Well the most prominent was Apache where I wondered about the total rq/s and volume, but I guess same goes for MySQL (but it's already integrated into Nominatim, for example).

> How do I set the default dashboard? I thought I had done everything I could - there is a public list which is set as the default view I thought?

Grafana >> Settings >> Preferences >> Home Dashboard, requires admin.

**Comment by tomhughes** [comment]
The squid dashboard should actually be removed because we don't have any squid instances running these days.

The discourse one I think somebody imported from somewhere and is mostly nonsense. There's another one that I started work on from scratch that hasn't been published yet.

The API database graphs look fine to me.

The temperature difference is expected - we deliberately put one PDUs sensor module on the cold side of the rack and the other on the hot side. Dublin is the same.

Using "all" for apache would not be very useful because we have a large number of apaches doing very different things so aggregating them doesn't make much sense. Service specific dashboards like www or nominatim where all the apaches are doing the same thing do allow aggregation.

**Comment by tomhughes** [comment]
Ah I broke that discourse dashboard last night when I was trying to bring it more in line with our others. I've fixed that now though there are some bits which don't work.

**Comment by pnorman** [comment]
> (At site Amsterdam it's weird that the two power supply have 12°C temp and 25% rel humidity difference, but that's not the dashboard's problem.)

This is expected due to the location of the sensors. We could label them hot/cold side.

> Grafana >> Settings >> Preferences >> Home Dashboard, requires admin.

We don't want to have a dashboard as default, we want a list of dashboards so you can pick which dashboard to view. This seems to be what's going on right now.

> Well the most prominent was Apache where I wondered about the total rq/s and volume, but I guess same goes for MySQL (but it's already integrated into Nominatim, for example).

I don't see total apache rq/s being useful, because this would sum across completely unrelated services. If you're using the apache, host, mysql, etc dashboards you're already on server-level investigations instead of service-level ones.

**Comment by grinapo** [comment]
> We don't want to have a dashboard as default, 

I think you do: it is called "Public" (aka l4dZY50Mz). 
Browse would work just like it does now, btw.

> > Well the most prominent was Apache where I wondered about the total rq/s and volume, but I guess same goes for MySQL (but it's already integrated into Nominatim, for example).
> 
> I don't see total apache rq/s being useful, because this would sum across completely unrelated services. If you're using the apache, host, mysql, etc dashboards you're already on server-level investigations instead of service-level ones.

I usually use multiselect lists, so it is possible to combine any or all graphs together. 
For most of us out here the server level graphs needed last, since I don't memorize the servers but any problems are visible in either by service or aggregated graphs.

But now I realised that some dashboards aren't visible in the Public unless **I scroll down**, for example Web Site or Tile Rendering (which seems to be aggregatable and service-level one). :relaxed:  My apologies.

**Comment by Firefishy** [comment]
Looks to me like most of the issues raised here have now been resolved. I will close the ticket. If there are new specific things that need resolving they can be raised separately.
