### ISSUE TITLE
Connect Dublin DB4 switches 10G ports to patch panel

### ISSUE THREAD

**Issue by grischard** [openstreetmap/operations#818]
Pre-connect the three 10G ports that are not in use to patch panel ports so that #642 and possible switchovers can happen without a rack visit.

**Comment by Firefishy** [comment]
There are SMF cables already on-site, but we can likely get spares if needed.

**Comment by Firefishy** [comment]
Cable already installed.

**Comment by Firefishy** [comment]
Only one link is installed, another can be installed later. Cable is not plugged in because we don't know port requirement yet. Additional cables are available in the box on rack shelf.

![PXL_20230206_122136418](https://user-images.githubusercontent.com/248188/217520054-b1f3ace0-5942-4912-a09b-99a764d642ef.jpg)
![PXL_20230206_123100944](https://user-images.githubusercontent.com/248188/217520061-df1ab4d2-48e1-4995-ae61-35322627e7c0.jpg)
![PXL_20230206_123103293](https://user-images.githubusercontent.com/248188/217520062-6c69f66d-53ec-4f8a-b59c-1664f2c35c65.jpg)
