### ISSUE TITLE
Getting refreshed tiles from https://tile.openstreetmap.org/

### ISSUE THREAD

**Issue by watmildon** [openstreetmap/operations#908]
Hello! I'm not sure where else to ask so feel free to ignore/redirect me.

I have a little [mastodon bot](https://en.osm.town/@SmallTownUSA) ([code here](https://github.com/watmildon/SmallCityMastodonBot)) that encourages folks to map small towns in the USA. I recently added functionality so that it will post an updated Carto image when folks reply to the bot "I mapped it!". Unfortunately, the request is always retrieving tiles from the cache and not freshly rendered tiles. 

An example reply is here: https://en.osm.town/@SmallTownUSA/110663852998497558

Also, if there's any other way to be a good citizen, I'm very happy to hear it. Thanks!

**Comment by grischard** [comment]
I understand from https://github.com/watmildon/SmallCityMastodonBot/issues/9 that you've been able to solve this?

**Comment by watmildon** [comment]
I have a workable solution. Thanks for doing the bookkeeping here!

**Comment by pnorman** [comment]
> I have a little [mastodon bot](https://en.osm.town/@SmallTownUSA) ([code here](https://github.com/watmildon/SmallCityMastodonBot)) that encourages folks to map small towns in the USA. I recently added functionality so that it will post an updated Carto image when folks reply to the bot "I mapped it!". Unfortunately, the request is always retrieving tiles from the cache and not freshly rendered tiles.

No. There are two possible scenarios. One is that you've requested it before the data makes it to the DB server. This takes about 2 minutes normally, so if someone toots faster than that and your bot requests the image, there's a chance the servers won't have the updates yet. The other is that tiles might still be in the CDN cache or tile server store. In this case, by design, you might get the cached tiles. We prohibit no-cache headers for load reasons, and ignore them from third-party apps or sites.

> Also, if there's any other way to be a good citizen, I'm very happy to hear it. Thanks!

Follow the policies in https://operations.osmfoundation.org/policies/tiles/, in particular user-agent requirements - the heavy usage requirements are not likely to be an issue for a properly coded bot that takes action after someone maps something.
